// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/serviceconn/gateway_file_service/pb/gw_file_svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBlogFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // int64 id = 4;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlogFileReq) Reset() {
	*x = UploadBlogFileReq{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlogFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogFileReq) ProtoMessage() {}

func (x *UploadBlogFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogFileReq.ProtoReflect.Descriptor instead.
func (*UploadBlogFileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBlogFileReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *UploadBlogFileReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadBlogFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadBlogFileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	NewFileName   string                 `protobuf:"bytes,4,opt,name=new_file_name,json=newFileName,proto3" json:"new_file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlogFileRes) Reset() {
	*x = UploadBlogFileRes{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlogFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogFileRes) ProtoMessage() {}

func (x *UploadBlogFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogFileRes.ProtoReflect.Descriptor instead.
func (*UploadBlogFileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBlogFileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UploadBlogFileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadBlogFileRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UploadBlogFileRes) GetNewFileName() string {
	if x != nil {
		return x.NewFileName
	}
	return ""
}

type GetBlogFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogFileReq) Reset() {
	*x = GetBlogFileReq{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogFileReq) ProtoMessage() {}

func (x *GetBlogFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogFileReq.ProtoReflect.Descriptor instead.
func (*GetBlogFileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlogFileReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetBlogFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetBlogFileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogFileRes) Reset() {
	*x = GetBlogFileRes{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogFileRes) ProtoMessage() {}

func (x *GetBlogFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogFileRes.ProtoReflect.Descriptor instead.
func (*GetBlogFileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlogFileRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBlogFileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetBlogFileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteBlogFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogFileReq) Reset() {
	*x = DeleteBlogFileReq{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogFileReq) ProtoMessage() {}

func (x *DeleteBlogFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogFileReq.ProtoReflect.Descriptor instead.
func (*DeleteBlogFileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBlogFileReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *DeleteBlogFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteBlogFileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogFileRes) Reset() {
	*x = DeleteBlogFileRes{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogFileRes) ProtoMessage() {}

func (x *DeleteBlogFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogFileRes.ProtoReflect.Descriptor instead.
func (*DeleteBlogFileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBlogFileRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteBlogFileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteBlogFileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UploadProfilePicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfilePicReq) Reset() {
	*x = UploadProfilePicReq{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePicReq) ProtoMessage() {}

func (x *UploadProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePicReq.ProtoReflect.Descriptor instead.
func (*UploadProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{6}
}

func (x *UploadProfilePicReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadProfilePicReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadProfilePicRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfilePicRes) Reset() {
	*x = UploadProfilePicRes{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePicRes) ProtoMessage() {}

func (x *UploadProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePicRes.ProtoReflect.Descriptor instead.
func (*UploadProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{7}
}

func (x *UploadProfilePicRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UploadProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadProfilePicRes) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetProfilePicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilePicReq) Reset() {
	*x = GetProfilePicReq{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilePicReq) ProtoMessage() {}

func (x *GetProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilePicReq.ProtoReflect.Descriptor instead.
func (*GetProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfilePicReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetProfilePicRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilePicRes) Reset() {
	*x = GetProfilePicRes{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilePicRes) ProtoMessage() {}

func (x *GetProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilePicRes.ProtoReflect.Descriptor instead.
func (*GetProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfilePicRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProfilePicRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteProfilePicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfilePicReq) Reset() {
	*x = DeleteProfilePicReq{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfilePicReq) ProtoMessage() {}

func (x *DeleteProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfilePicReq.ProtoReflect.Descriptor instead.
func (*DeleteProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProfilePicReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteProfilePicRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfilePicRes) Reset() {
	*x = DeleteProfilePicRes{}
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfilePicRes) ProtoMessage() {}

func (x *DeleteProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfilePicRes.ProtoReflect.Descriptor instead.
func (*DeleteProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProfilePicRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteProfilePicRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto protoreflect.FileDescriptor

const file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc = "" +
	"\n" +
	":apis/serviceconn/gateway_file_service/pb/gw_file_svc.proto\x12\bauth_svc\"]\n" +
	"\x11UploadBlogFileReq\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"u\n" +
	"\x11UploadBlogFileRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\"\n" +
	"\rnew_file_name\x18\x04 \x01(\tR\vnewFileName\"F\n" +
	"\x0eGetBlogFileReq\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"R\n" +
	"\x0eGetBlogFileRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"I\n" +
	"\x11DeleteBlogFileReq\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"[\n" +
	"\x11DeleteBlogFileRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"_\n" +
	"\x13UploadProfilePicReq\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"`\n" +
	"\x13UploadProfilePicRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"H\n" +
	"\x10GetProfilePicReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"V\n" +
	"\x10GetProfilePicRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"K\n" +
	"\x13DeleteProfilePicReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"]\n" +
	"\x13DeleteProfilePicRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xec\x03\n" +
	"\x0eUploadBlogFile\x12T\n" +
	"\x10UploadProfilePic\x12\x1d.auth_svc.UploadProfilePicReq\x1a\x1d.auth_svc.UploadProfilePicRes\"\x00(\x01\x12K\n" +
	"\rGetProfilePic\x12\x1a.auth_svc.GetProfilePicReq\x1a\x1a.auth_svc.GetProfilePicRes\"\x000\x01\x12R\n" +
	"\x10DeleteProfilePic\x12\x1d.auth_svc.DeleteProfilePicReq\x1a\x1d.auth_svc.DeleteProfilePicRes\"\x00\x12N\n" +
	"\x0eUploadBlogFile\x12\x1b.auth_svc.UploadBlogFileReq\x1a\x1b.auth_svc.UploadBlogFileRes\"\x00(\x01\x12E\n" +
	"\vGetBlogFile\x12\x18.auth_svc.GetBlogFileReq\x1a\x18.auth_svc.GetBlogFileRes\"\x000\x01\x12L\n" +
	"\x0eDeleteBlogFile\x12\x1b.auth_svc.DeleteBlogFileReq\x1a\x1b.auth_svc.DeleteBlogFileRes\"\x00B,Z*./apis/serviceconn/gateway_file_service/pbb\x06proto3"

var (
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData []byte
)

func file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc), len(file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc)))
	})
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData
}

var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_goTypes = []any{
	(*UploadBlogFileReq)(nil),   // 0: auth_svc.UploadBlogFileReq
	(*UploadBlogFileRes)(nil),   // 1: auth_svc.UploadBlogFileRes
	(*GetBlogFileReq)(nil),      // 2: auth_svc.GetBlogFileReq
	(*GetBlogFileRes)(nil),      // 3: auth_svc.GetBlogFileRes
	(*DeleteBlogFileReq)(nil),   // 4: auth_svc.DeleteBlogFileReq
	(*DeleteBlogFileRes)(nil),   // 5: auth_svc.DeleteBlogFileRes
	(*UploadProfilePicReq)(nil), // 6: auth_svc.UploadProfilePicReq
	(*UploadProfilePicRes)(nil), // 7: auth_svc.UploadProfilePicRes
	(*GetProfilePicReq)(nil),    // 8: auth_svc.GetProfilePicReq
	(*GetProfilePicRes)(nil),    // 9: auth_svc.GetProfilePicRes
	(*DeleteProfilePicReq)(nil), // 10: auth_svc.DeleteProfilePicReq
	(*DeleteProfilePicRes)(nil), // 11: auth_svc.DeleteProfilePicRes
}
var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_depIdxs = []int32{
	6,  // 0: auth_svc.UploadBlogFile.UploadProfilePic:input_type -> auth_svc.UploadProfilePicReq
	8,  // 1: auth_svc.UploadBlogFile.GetProfilePic:input_type -> auth_svc.GetProfilePicReq
	10, // 2: auth_svc.UploadBlogFile.DeleteProfilePic:input_type -> auth_svc.DeleteProfilePicReq
	0,  // 3: auth_svc.UploadBlogFile.UploadBlogFile:input_type -> auth_svc.UploadBlogFileReq
	2,  // 4: auth_svc.UploadBlogFile.GetBlogFile:input_type -> auth_svc.GetBlogFileReq
	4,  // 5: auth_svc.UploadBlogFile.DeleteBlogFile:input_type -> auth_svc.DeleteBlogFileReq
	7,  // 6: auth_svc.UploadBlogFile.UploadProfilePic:output_type -> auth_svc.UploadProfilePicRes
	9,  // 7: auth_svc.UploadBlogFile.GetProfilePic:output_type -> auth_svc.GetProfilePicRes
	11, // 8: auth_svc.UploadBlogFile.DeleteProfilePic:output_type -> auth_svc.DeleteProfilePicRes
	1,  // 9: auth_svc.UploadBlogFile.UploadBlogFile:output_type -> auth_svc.UploadBlogFileRes
	3,  // 10: auth_svc.UploadBlogFile.GetBlogFile:output_type -> auth_svc.GetBlogFileRes
	5,  // 11: auth_svc.UploadBlogFile.DeleteBlogFile:output_type -> auth_svc.DeleteBlogFileRes
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_init() }
func file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_init() {
	if File_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc), len(file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto = out.File
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_goTypes = nil
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_depIdxs = nil
}
