package constants

const (
	Register                     = "Joined"
	Login                        = "Logged in"
	ForgotPassword               = "Accessed forgot password api"
	VerifiedEmailForPassChange   = "Verified email to change the password"
	UpdatedPassword              = "Updated the password"
	Logout                       = "Logged Out"
	UpdateProfile                = "Updated the profile information"
	RequestForEmailVerification  = "Requested Email Verification"
	VerifyEmail                  = "Verified Email"
	UserStatusChange             = "Changed User Status"
	UserDeactivated              = "Deactivated User"
	UserActivated                = "Activated User"
	UpdateProfilePic             = "Updated Profile Picture"
	RemoveProfilePic             = "Removed Profile Picture"
	UpdatedUserName              = "Updated username"
	ChangedEmail                 = "Changed Email"
	ChangedVisibilityToAnonymous = "Changed Visibility to Anonymous"
	ChangedVisibilityToPublic    = "Changed Visibility to Public"
	FollowedTopics               = "Followed topics: %v"
	UnFollowedTopics             = "Un-followed topics: %v"
	CreatedTopics                = "Created topics: %v"
	FollowedUser                 = "Followed a User: %v"
	UnFollowUser                 = "Un-Followed a User: %v"

	AddedInstagram = "Added Instagram"
	AddedTwitter   = "Added Twitter"

	CreateBlog               = "Created a Blog %s"
	UpdateDraftedBlog        = "Updated the Drafted Blog"
	UpdateBlog               = "Updated the Blog"
	DeleteBlog               = "Deleted the Blog %s"
	PublishBlog              = "Published the Blog %s"
	ArchiveBlog              = "Archived the Blog"
	LikeBlog                 = "Liked a Blog %s"
	UnlikeBlog               = "Unliked a Blog %s"
	CommentBlog              = "Commented on a Blog"
	ShareBlog                = "Shared a Blog with %s"
	TransferredBlogOwnership = "Transferred Blog Ownership to %s"
	InvitedAsACoAuthor       = "Invited %s as a Co-Author for blog id %s"
	RevokedCoAuthorRequest   = "Removed %s from Co-Author for blog id %s"
	RemovedFromCoAuthor      = "Removed %s from Co-Author"
	GotInvitedAsACoAuthor    = "Invited by %s as a Co-Author"
	GotRemovedFromCoAuthor   = "Removed by %s form a Co-Author"
	DeclinedCoAuthor         = "Declined co-author request of %s"
	JoinedAsCoAuthor         = "Joined as a Co-Author"
	UpdatedABlogAsCoAuthor   = "Updated a Blog as a Co-Author"
	PublishedABlogAsCoAuthor = "Published a Blog as a Co-Author"
	ArchivedABlogAsCoAuthor  = "Archived a Blog as a Co-Author"
	DraftedABlogAsCoAuthor   = "Drafted a Blog as a Co-Author"
	BookMarkedBlog           = "Bookmarked a Blog, blog id %s"
	RemoveBookMark           = "Removed Bookmark from a Blog, blog id %s"
)
