package constants

var Business = []string{
	"Business",
	"Finance",
	"Economy",
	"Nova Chemicals",
	"Corporate Layoffs",
	"Chinese automakers",
	"Energy Sector",
	"Budget Efficiency",
	"Price hike",
	"Mubadala",
	"Credit Suisse",
	"Business and Finance",
	"Profit growth",
	"Salesforce Layoffs",
	"Infrastructure",
	"Food delivery industry",
	"Subscriber decline",
	"Salesforce",
	"SupplyChain",
	"Petrochemicals",
	"NetworkingTools",
	"Mergers & Acquisitions",
	"Global Trade Compliance",
	"Digital Transformation",
	"V-Day revenue",
	"Gig Economy",
	"Romance industry",
	"Indian tech market",
	"Venture Capital",
	"Brands",
	"AdaniGroup",
	"Corporate profits",
	"IT Management",
	"JobCuts",
	"India manufacturing",
	"FutureOfWork",
	"Small Business",
	"InfrastructureDevelopment",
	"DigitalTransformation",
	"Global Mergers",
	"DEI rollback",
	"Pharmaceutical industry",
	"Workplace equity",
	"Layoffs2025",
	"Prosus acquisition",
	"Freelancing",
	"Nothing growth",
	"Polyolefins",
	"OMV",
	"Export Controls",
	"Market Analysis",
	"Post-pandemic trends",
	"Retail trends",
	"Acquisition",
	"TravelPerk",
	"Malaysia e-invoicing",
	"Adani",
	"Global EV market",
	"Economics",
	"Organizational impact",
	"Corporate diversity",
	"Layoffs",
	"Startups",
	"Disney earnings",
	"Private-sector funding",
	"Corporate compliance",
	"Adani Greens",
	"Tax rules for nomads",
	"Cost-Effective Innovation",
	"Grubhub sale",
	"Blinkit",
	"CorporateLeadership",
	"Careers",
	"Tesla competition",
	"AI subscriptions",
	"LogisticsEfficiency",
	"UBS Group",
	"Entrepreneurship",
	"TechAcquisition",
	"ADNOC",
	"Startup Funding",
	"InterestRates",
	"State pension",
	"Investing",
	"StockMarket",
	"Philanthropy",
	"DigitalFinance",
	"Retirement",
	"FinTech",
	"Money",
	"ShortSelling",
	"Pensions",
	"UK pensions",
	"Investment",
	"Hindenburg Research",
	"InterestRateHike",
	"Real Estate",
	"Pension increase",
	"401k",
	"BankOfAmerica",
	"Stock market news",
	"Triple lock",
	"Retirement income",
	"Banking Sector",
}

var Technology = []string{
	"Hardware and IOTs",
	"Robotics",
	"BatteryTech",
	"Smartphone revolution",
	"Blockchain",
	"Data Center",
	"IoT Development",
	"SmartCities",
	"Mobiles",
	"Compact camera",
	"Speed of light camera",
	"Video-calling apps",
	"TechInnovation",
	"Fintech",
	"TechIndustry",
	"Smartphone technology",
	"Embedded Systems",
	"Meta-lenses",
	"IoT Projects",
	"STM32",
	"Embedded Development",
	"AI Chips",
	"Semiconductor Industry",
	"Software",
	"Distributed technology",
	"ESP32",
	"Technology compliance",
	"AI Data Center",
	"Mobile World Congress",
	"Microkernel architecture",
	"Germany tech",
	"Tech ecosystem",
	"TechNews",
	"Tech nostalgia",
	"Border control technology",
	"TechComparison",
	"Communication tools",
	"Electric car trends",
	"ElectricVehicles",
	"Tech Regulations",
	"Microcontrollers",
	"EVInnovation",
	"Open Source",
	"AI chip",
	"Pixel smartphones",
	"Monkeys",
	"Twitter",
	"BladeBattery",
	"Microsoft news",
	"AMD",
	"Disney+",
	"End of Skype",
	"Ear (1)",
	"Phone (1)",
	"MediaTek",
	"DeepSeek AI",
	"BYD2025",
	"Skype shutdown",
	"Google",
	"Reddit",
	"Just Eat Takeaway",
	"Xiaomi electric vehicles",
	"Qualcomm",
	"Xiaomi 15 Ultra",
	"Apple",
	"Amazon",
	"Anthropic",
	"Xiaomi",
	"Google hardware",
	"BYD FastCharging",
	"Tiktok",
	"Huawei ecosystem",
	"Nothing smartphone",
	"SU7 Ultra",
	"Microsoft",
	"Meta",
	"Mastodon",
	"Google Tensor",
	"Binance",
	"Perplexity AI",
	"Microsoft Teams",
	"BigTech",
	"Just Eat",
	"Accenture",
	"OpenAI",
	"Nvidia",
	"Medium",
	"Tech",
	"GlobalTech",
	"Samsung Galaxy S25 Ultra",
	"API Design",
	"DigitalSurveillance",
	"5G",
	"Phishing Attack",
	"Tech Future",
	"Semiconductors",
	"Agentforce",
	"Tech Innovation",
	"Super Computer",
	"SiliconValley",
	"Gmail",
	"Web",
	"LTS (Long Term Support)",
	"Snapdragon8",
	"Snapdragon 8 Gen 4",
	"TechInnovation",
	"System Design",
	"Backend Development",
	"Web Push Notification",
	"Chip",
	"DataPrivacy",
	"DevOps Practices",
	"Reverse Proxy",
	"Technology",
	"PaloAltoNetworks",
	"TechNews",
	"Go Programming",
	"Frontend Engineering",
	"SoftwareDevelopment",
	"Developer Tools",
	"HighPerformanceComputing",
	"MemoryManagement",
	"Performance Optimization",
	"Mobile Development",
	"Benchmarking",
	"Golang",
	"Software Development",
	"Go Modules",
	"ModernProgramming",
	"Coding",
	"ProgrammingTrends",
	"web Development",
	"Multithreading",
	"SystemsProgramming",
	"Android Development",
	"Upgrade Guide",
	"Runtime Improvements",
	"WebAssembly",
	"GameDevelopment",
	"Flutter",
	"Software Engineering",
	"Go 1.24",
	"Backward Compatibility",
	"Testing",
	"Memory Management",
	"TinyGo",
	"LowLevelProgramming",
	"Odin",
	"Code Optimization",
	"WASM",
	"Concurrency",
	"Weak Pointers",
	"Go Tools",
	"IOS Development",
	"Programming",
	"Tech",
	"AI Agents",
	"Data Engineering",
	"Automation",
	"Machine Learning",
	"Google Cloud",
	"BigQuery",
	"Google Gemini",
}

var Sports = []string{
	"Premier League",
	"World Cup",
	"NottinghamForest",
	"Young talent",
	"Raphinha",
	"F1PreSeason",
	"Sports",
	"Benfica",
	"Formula1",
	"UEFAChampionsLeague",
	"NFL",
	"Barcelona",
	"Real Madrid",
	"Olympics",
	"men's cricket",
	"Bundesliga 2025",
	"LiverpoolVsForest",
	"Los Angeles Lakers",
	"Handball",
	"IHFWorldChampionship",
	"SF25",
	"Lamine Yamal",
	"ScuderiaFerrari",
	"FIFAWorldCup",
	"BahrainGP",
	"cricket",
	"HamiltonFerrari",
	"Baseball",
	"MotoGP",
	"Sepang Circuit",
	"NBA",
	"AFC Champions League",
	"Soccer",
	"BarcaVsMadrid",
	"Las Palmas",
	"TitleRace",
	"Ferrari",
	"PremierLeague",
	"Utah Jazz",
	"Wolfsburg vs Bayern Munich",
	"Australian Open",
	"Sports Injury",
	"Tennis",
	"Champions League",
	"F1Testing",
	"Liverpool",
	"Bundesliga Highlights",
	"HandballChampionship",
	"La Liga",
	"CroatiaVsHungary",
	"Racing",
	"rma vs las palmas",
	"Basketball",
	"SpanishSuperCup",
	"SuperBowl",
	"Barcelona news",
	"LewisHamilton",
	"Football",
	"LFC",
	"Champions League records",
	"Lakers vs. Jazz",
	"SportsTourism",
	"Motorsport",
	"Bayern Munich",
	"Novak Djokovic",
	"Jorge Martin",
	"ChrisWood",
	"DiogoJota",
	"Luka Dončić",
	"Alex Zverev",
	"Leon Goretzka",
	"Lorenzo Savadori",
	"MatzSels",
	"Vincent Kompany",
	"Lionel Messi",
	"Kylian Mbappe",
	"Cristiano Ronaldo",
}

var Science = []string{
	"Science",
	"Jezero Crater",
	"Space Exploration",
	"MultiverseTheory",
	"BigBangTheory",
	"Science",
	"Medicine",
	"Geology",
	"Biotechnology",
	"Quantum Computing",
	"Space Research",
	"Agriculture",
	"Space",
	"Neuroscience",
	"SpaceX Rival",
	"BlackHoleCosmology",
	"Tethys Ocean",
	"GalaxyRotation",
	"Science History",
	"UK Space Industry",
	"European Space Agency",
	"Geography",
	"Geoid low",
	"Perseverance Rover",
	"Genetics",
	"Ecology",
	"OSIRIS-REx",
	"Tectonic plates",
	"Chemistry",
	"Research",
	"Nuclear Disaster",
	"Maths",
	"Physics",
	"UniverseInsideBlackHole",
	"Mantle plumes",
	"Geological research",
	"Healthcare",
	"Sustainable Rockets",
}

var Health = []string{
	"Health",
	"Fitness",
	"Sleep",
	"Stillbirth",
	"Safety",
	"Coronavirus",
	"Breast Ultrasound",
	"Vaccines",
	"Weight Management",
	"Exercise",
	"Womens Health",
	"Death And Dying",
	"Weight Loss",
	"BMI",
	"Trans Healthcare",
	"Breast Cancer",
	"Lesion Classification",
	"Covid Vaccine",
	"World Health Organization",
	"Mens Health",
	"Aging",
	"Disease",
	"Covid-19",
	"Nutrition",
	"Surgery",
	"Heart Health",
	"Obesity",
	"Traditional medicine",
	"Self-Care",
	"CortisolManagement",
	"Five elements healing",
	"Nature connection",
	"Ayurveda",
	"Yoga and Meditation",
	"Work Culture",
	"Telemedicine",
	"Nutrition Science",
	"Sleep Disorder",
	"Healthy Lifestyle",
	"Covid19",
	"Holistic health",
	"Natural healing",
	"Air sun earth water fire",
	"Public Health",
}

var Entertainment = []string{
	"Night Life",
	"Music",
	"Ashton Kutcher",
	"Pop Culture",
	"The Ranch TV Show",
	"Kaley Cuoco",
	"Humour",
	"Jim Parsons",
	"Rural Comedy",
	"Oscars 2025",
	"MissWorld2024",
	"Sitcoms",
	"Squid Game 2",
	"Netflix Originals",
	"Entertainment industry",
	"Movies",
	"The Big Bang Theory",
	"Chernobyl Series",
	"Television",
	"Danny Masterson",
	"Disney Plus",
	"TV Show Appearances",
	"Gaming",
	"Anime",
	"Sam Elliott",
	"Sheldon Cooper",
	"Streaming services",
	"Comedy Series",
	"Celebrity Guest Stars",
	"Mindhunter",
	"Streaming",
	"MissWorldIndia",
	"Hulu",
	"Reality TV",
	"Tv Reviews",
	"Netflix",
	"Hbo Max",
	"TV Shows",
}

var Travel = []string{
	"Passport-free travel",
	"EU Passport",
	"Hidden gems Prague",
	"Indian Hospitality",
	"Sustainable Travel",
	"Traveler’s Diary",
	"International travel",
	"Travel",
	"Corporate Travel",
	"Travel Writing",
	"Indian travelers",
	"Tourist Statistics",
	"Old Town secrets",
	"Tourism Realities",
	"Group travel to Russia",
	"Challenges in Indian Tourism",
	"Vacation",
	"Travel Challenges",
	"Post-pandemic tourism",
	"Travel in India",
	"Traveler’s Voice",
	"Slovenia Tourism",
	"Tourism Pros and Cons",
	"Singapore QR code entry",
	"European Destinations",
	"Tourism Critique",
	"Firsthand Travel Experience",
	"Travel Benefits",
	"Prague City Tourism",
	"Moscow tourism",
	"India Tourism",
	"Tourism Insights",
	"Travel Expectations vs Reality",
	"Travel Reflections",
	"Changi Airport",
	"Scandinavia",
	"Prague guided tours",
	"Adventure Tourism",
	"Tourism",
	"Tourism Analysis",
	"Travel Trends",
	"Travel",
	"Immigration",
}

var Food = []string{
	"Food",
	"Global coffee rankings",
	"Tea",
	"Coffee",
	"Food and Cuisine",
	"Prague cafés",
	"Restaurants",
	"Specialty coffee",
	"Foodies",
	"Baking",
	"World’s best coffee shops",
	"The Miners Prague",
	"Sustainability in coffee",
	"Czech coffee culture",
	"Cooking",
}

var Lifestyle = []string{
	"Lifestyle",
	"Vibe",
	"Fashion",
}

var Education = []string{
	"EducationForAll",
	"Public Schools",
	"Higher Education",
	"TU Munich",
	"Study Abroad",
	"FinancialLiteracy",
	"Charter Schools",
	"Student Loans",
	"Education Reform",
	"Teaching",
	"PhD",
	"Indian Institute of Science",
}

var Space = []string{
	"Space",
	"space science",
	"NASA",
	"ISS",
	"Space exploration",
	"Crew-10 mission",
	"JamesWebb",
	"LongestSpaceflights",
	"Falcon 9 rocket",
	"JWSTDiscoveries",
	"SpaceExploration",
	"AstronautRecords",
	"MirStation",
	"Delayed launch",
	"Roscosmos",
	"HumanInSpace",
	"International Space Station",
	"Astrophysics",
	"Orbex",
	"Astronomy",
	"Astrophysics",
	"CosmicMystery",
	"Indian Ocean gravity hole",
	"Elephants Foot",
	"Mars",
	"Earth’s gravitational anomaly",
	"Light Pollution",
	"Blue Origin",
	"Asteroid Bennu",
	"Space Programs",
	"SpaceX",
}

var PhilosophyAndPsychology = []string{
	"Stoicism",
	"Ethics",
	"Existentialism",
	"Atheism",
	"Metaphysics",
	"Morality",
	"Epistemology",
	"Philosophy Of Mind",
	"Psychology tips",
	"Psychology",
	"Philosophy",
}

var Humor = []string{
	"Humor",
	"ComedyJokes",
	"Parody",
	"Satire",
	"Stand Up Comedy",
	"Comedy",
	"Jokes",
	"Meme",
	"Memes",
}

var BlackListedTopics = []string{
	"Politics",
	"Religion",
	"Violence",
	"Sexual Content",
	"Illegal Activities",
	"Discrimination",
}
