# Production docker-compose override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3.8'

services:
  the_monkeys_authz:
    build:
      dockerfile: microservices/the_monkeys_authz/Dockerfile.distroless
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Remove volumes in production (code is baked into image)
    volumes: []

  the_monkeys_blog:
    build:
      dockerfile: microservices/the_monkeys_blog/Dockerfile.distroless
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.7'
        reservations:
          memory: 128M
          cpus: '0.2'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Remove volumes in production (code is baked into image)
    volumes: []