// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/serviceconn/gateway_cache/pb/gw_cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetRequest represents a request to set a value in the cache
type SetRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value             []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ExpirationSeconds int64                  `protobuf:"varint,3,opt,name=expiration_seconds,json=expirationSeconds,proto3" json:"expiration_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetExpirationSeconds() int64 {
	if x != nil {
		return x.ExpirationSeconds
	}
	return 0
}

// SetResponse represents the response from a Set operation
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetRequest represents a request to get a value from the cache
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse represents the response from a Get operation
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DeleteRequest represents a request to delete a key from the cache
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResponse represents the response from a Delete operation
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ClearRequest represents a request to clear all items from the cache
type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{6}
}

// ClearResponse represents the response from a Clear operation
type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{7}
}

func (x *ClearResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetStatsRequest represents a request to get cache statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{8}
}

// GetStatsResponse represents the response containing cache statistics
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Expired       int32                  `protobuf:"varint,3,opt,name=expired,proto3" json:"expired,omitempty"`
	Active        int32                  `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStatsResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GetStatsResponse) GetExpired() int32 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *GetStatsResponse) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *GetStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apis_serviceconn_gateway_cache_pb_gw_cache_proto protoreflect.FileDescriptor

const file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDesc = "" +
	"\n" +
	"0apis/serviceconn/gateway_cache/pb/gw_cache.proto\x12\tcache_svc\"c\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12-\n" +
	"\x12expiration_seconds\x18\x03 \x01(\x03R\x11expirationSeconds\"=\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"S\n" +
	"\vGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0e\n" +
	"\fClearRequest\"?\n" +
	"\rClearResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fGetStatsRequest\"\x95\x01\n" +
	"\x10GetStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x18\n" +
	"\aexpired\x18\x03 \x01(\x05R\aexpired\x12\x16\n" +
	"\x06active\x18\x04 \x01(\x05R\x06active\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\xc4\x02\n" +
	"\fCacheService\x126\n" +
	"\x03Set\x12\x15.cache_svc.SetRequest\x1a\x16.cache_svc.SetResponse\"\x00\x126\n" +
	"\x03Get\x12\x15.cache_svc.GetRequest\x1a\x16.cache_svc.GetResponse\"\x00\x12?\n" +
	"\x06Delete\x12\x18.cache_svc.DeleteRequest\x1a\x19.cache_svc.DeleteResponse\"\x00\x12<\n" +
	"\x05Clear\x12\x17.cache_svc.ClearRequest\x1a\x18.cache_svc.ClearResponse\"\x00\x12E\n" +
	"\bGetStats\x12\x1a.cache_svc.GetStatsRequest\x1a\x1b.cache_svc.GetStatsResponse\"\x00B%Z#./apis/serviceconn/gateway_cache/pbb\x06proto3"

var (
	file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescData []byte
)

func file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDesc), len(file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDesc)))
	})
	return file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDescData
}

var file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_goTypes = []any{
	(*SetRequest)(nil),       // 0: cache_svc.SetRequest
	(*SetResponse)(nil),      // 1: cache_svc.SetResponse
	(*GetRequest)(nil),       // 2: cache_svc.GetRequest
	(*GetResponse)(nil),      // 3: cache_svc.GetResponse
	(*DeleteRequest)(nil),    // 4: cache_svc.DeleteRequest
	(*DeleteResponse)(nil),   // 5: cache_svc.DeleteResponse
	(*ClearRequest)(nil),     // 6: cache_svc.ClearRequest
	(*ClearResponse)(nil),    // 7: cache_svc.ClearResponse
	(*GetStatsRequest)(nil),  // 8: cache_svc.GetStatsRequest
	(*GetStatsResponse)(nil), // 9: cache_svc.GetStatsResponse
}
var file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_depIdxs = []int32{
	0, // 0: cache_svc.CacheService.Set:input_type -> cache_svc.SetRequest
	2, // 1: cache_svc.CacheService.Get:input_type -> cache_svc.GetRequest
	4, // 2: cache_svc.CacheService.Delete:input_type -> cache_svc.DeleteRequest
	6, // 3: cache_svc.CacheService.Clear:input_type -> cache_svc.ClearRequest
	8, // 4: cache_svc.CacheService.GetStats:input_type -> cache_svc.GetStatsRequest
	1, // 5: cache_svc.CacheService.Set:output_type -> cache_svc.SetResponse
	3, // 6: cache_svc.CacheService.Get:output_type -> cache_svc.GetResponse
	5, // 7: cache_svc.CacheService.Delete:output_type -> cache_svc.DeleteResponse
	7, // 8: cache_svc.CacheService.Clear:output_type -> cache_svc.ClearResponse
	9, // 9: cache_svc.CacheService.GetStats:output_type -> cache_svc.GetStatsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_init() }
func file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_init() {
	if File_apis_serviceconn_gateway_cache_pb_gw_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDesc), len(file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_cache_pb_gw_cache_proto = out.File
	file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_goTypes = nil
	file_apis_serviceconn_gateway_cache_pb_gw_cache_proto_depIdxs = nil
}
