// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: apis/serviceconn/gateway_authz/pb/gw_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest_LoginMethod int32

const (
	RegisterUserRequest_The_MONKEYS RegisterUserRequest_LoginMethod = 0
	RegisterUserRequest_GOOGLE_ACC  RegisterUserRequest_LoginMethod = 1
	RegisterUserRequest_ANDROID     RegisterUserRequest_LoginMethod = 2
	RegisterUserRequest_IPHONE      RegisterUserRequest_LoginMethod = 3
)

// Enum value maps for RegisterUserRequest_LoginMethod.
var (
	RegisterUserRequest_LoginMethod_name = map[int32]string{
		0: "The_MONKEYS",
		1: "GOOGLE_ACC",
		2: "ANDROID",
		3: "IPHONE",
	}
	RegisterUserRequest_LoginMethod_value = map[string]int32{
		"The_MONKEYS": 0,
		"GOOGLE_ACC":  1,
		"ANDROID":     2,
		"IPHONE":      3,
	}
)

func (x RegisterUserRequest_LoginMethod) Enum() *RegisterUserRequest_LoginMethod {
	p := new(RegisterUserRequest_LoginMethod)
	*p = x
	return p
}

func (x RegisterUserRequest_LoginMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterUserRequest_LoginMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_enumTypes[0].Descriptor()
}

func (RegisterUserRequest_LoginMethod) Type() protoreflect.EnumType {
	return &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_enumTypes[0]
}

func (x RegisterUserRequest_LoginMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterUserRequest_LoginMethod.Descriptor instead.
func (RegisterUserRequest_LoginMethod) EnumDescriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{0, 0}
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	FirstName     string                          `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                          `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                          `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                          `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	LoginMethod   RegisterUserRequest_LoginMethod `protobuf:"varint,5,opt,name=login_method,json=loginMethod,proto3,enum=auth_svc.RegisterUserRequest_LoginMethod" json:"login_method,omitempty"`
	IpAddress     string                          `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                          `protobuf:"bytes,7,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetLoginMethod() RegisterUserRequest_LoginMethod {
	if x != nil {
		return x.LoginMethod
	}
	return RegisterUserRequest_The_MONKEYS
}

func (x *RegisterUserRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterUserRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type RegisterUserResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StatusCode              int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Token                   string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EmailVerified           bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	UserId                  int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username                string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	FirstName               string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationStatus string                 `protobuf:"bytes,9,opt,name=email_verification_status,json=emailVerificationStatus,proto3" json:"email_verification_status,omitempty"`
	Error                   *Error                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	AccountId               string                 `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegisterUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterUserResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *RegisterUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserResponse) GetEmailVerificationStatus() string {
	if x != nil {
		return x.EmailVerificationStatus
	}
	return ""
}

func (x *RegisterUserResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RegisterUserResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	AccountId     string                 `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ValidateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ValidateResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ValidateResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DecodeSignedJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeSignedJWTRequest) Reset() {
	*x = DecodeSignedJWTRequest{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeSignedJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeSignedJWTRequest) ProtoMessage() {}

func (x *DecodeSignedJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeSignedJWTRequest.ProtoReflect.Descriptor instead.
func (*DecodeSignedJWTRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{5}
}

func (x *DecodeSignedJWTRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DecodeSignedJWTResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StatusCode              int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	UserId                  int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username                string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FirstName               string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationStatus string                 `protobuf:"bytes,7,opt,name=email_verification_status,json=emailVerificationStatus,proto3" json:"email_verification_status,omitempty"`
	Error                   *Error                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	AccountId               string                 `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DecodeSignedJWTResponse) Reset() {
	*x = DecodeSignedJWTResponse{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeSignedJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeSignedJWTResponse) ProtoMessage() {}

func (x *DecodeSignedJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeSignedJWTResponse.ProtoReflect.Descriptor instead.
func (*DecodeSignedJWTResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DecodeSignedJWTResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DecodeSignedJWTResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DecodeSignedJWTResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DecodeSignedJWTResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *DecodeSignedJWTResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *DecodeSignedJWTResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DecodeSignedJWTResponse) GetEmailVerificationStatus() string {
	if x != nil {
		return x.EmailVerificationStatus
	}
	return ""
}

func (x *DecodeSignedJWTResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DecodeSignedJWTResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type AccessCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	BlogId        string                 `protobuf:"bytes,5,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessCheckReq) Reset() {
	*x = AccessCheckReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckReq) ProtoMessage() {}

func (x *AccessCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckReq.ProtoReflect.Descriptor instead.
func (*AccessCheckReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AccessCheckReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccessCheckReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccessCheckReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccessCheckReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccessCheckReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *AccessCheckReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type AccessCheckRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Access        []string               `protobuf:"bytes,5,rep,name=access,proto3" json:"access,omitempty"`
	BlogId        string                 `protobuf:"bytes,6,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Role          string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessCheckRes) Reset() {
	*x = AccessCheckRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessCheckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCheckRes) ProtoMessage() {}

func (x *AccessCheckRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCheckRes.ProtoReflect.Descriptor instead.
func (*AccessCheckRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{8}
}

func (x *AccessCheckRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AccessCheckRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccessCheckRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccessCheckRes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccessCheckRes) GetAccess() []string {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *AccessCheckRes) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *AccessCheckRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AccessCheckRes) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginUserRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginUserRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type LoginUserResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StatusCode              int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Token                   string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EmailVerified           bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	UserId                  int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username                string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	FirstName               string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationStatus string                 `protobuf:"bytes,9,opt,name=email_verification_status,json=emailVerificationStatus,proto3" json:"email_verification_status,omitempty"`
	Error                   *Error                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	AccountId               string                 `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LoginUserResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LoginUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginUserResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *LoginUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *LoginUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *LoginUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserResponse) GetEmailVerificationStatus() string {
	if x != nil {
		return x.EmailVerificationStatus
	}
	return ""
}

func (x *LoginUserResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *LoginUserResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ForgotPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordReq) Reset() {
	*x = ForgotPasswordReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordReq) ProtoMessage() {}

func (x *ForgotPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordReq.ProtoReflect.Descriptor instead.
func (*ForgotPasswordReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ForgotPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgotPasswordReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ForgotPasswordReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type ForgotPasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRes) Reset() {
	*x = ForgotPasswordRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRes) ProtoMessage() {}

func (x *ForgotPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRes.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ForgotPasswordRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForgotPasswordRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForgotPasswordRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ResetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,6,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ResetPasswordReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResetPasswordReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResetPasswordReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ResetPasswordReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type ResetPasswordRes struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StatusCode              int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Token                   string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EmailVerified           bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	UserId                  int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName                string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName               string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationStatus bool                   `protobuf:"varint,9,opt,name=email_verification_status,json=emailVerificationStatus,proto3" json:"email_verification_status,omitempty"`
	Error                   *Error                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResetPasswordRes) Reset() {
	*x = ResetPasswordRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRes) ProtoMessage() {}

func (x *ResetPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRes.ProtoReflect.Descriptor instead.
func (*ResetPasswordRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResetPasswordRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRes) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *ResetPasswordRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResetPasswordRes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ResetPasswordRes) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ResetPasswordRes) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ResetPasswordRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRes) GetEmailVerificationStatus() bool {
	if x != nil {
		return x.EmailVerificationStatus
	}
	return false
}

func (x *ResetPasswordRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdatePasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdatePasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdatePasswordReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UpdatePasswordReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UpdatePasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRes) Reset() {
	*x = UpdatePasswordRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRes) ProtoMessage() {}

func (x *UpdatePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRes.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePasswordRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdatePasswordRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type EmailVerificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerificationReq) Reset() {
	*x = EmailVerificationReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationReq) ProtoMessage() {}

func (x *EmailVerificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationReq.ProtoReflect.Descriptor instead.
func (*EmailVerificationReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{17}
}

func (x *EmailVerificationReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailVerificationReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *EmailVerificationReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type EmailVerificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerificationRes) Reset() {
	*x = EmailVerificationRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationRes) ProtoMessage() {}

func (x *EmailVerificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationRes.ProtoReflect.Descriptor instead.
func (*EmailVerificationRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{18}
}

func (x *EmailVerificationRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmailVerificationRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type VerifyEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailReq) Reset() {
	*x = VerifyEmailReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailReq) ProtoMessage() {}

func (x *VerifyEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailReq.ProtoReflect.Descriptor instead.
func (*VerifyEmailReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyEmailReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyEmailReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyEmailReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *VerifyEmailReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type VerifyEmailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRes) Reset() {
	*x = VerifyEmailRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRes) ProtoMessage() {}

func (x *VerifyEmailRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRes.ProtoReflect.Descriptor instead.
func (*VerifyEmailRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyEmailRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *VerifyEmailRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *VerifyEmailRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateUsernameReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentUsername string                 `protobuf:"bytes,1,opt,name=current_username,json=currentUsername,proto3" json:"current_username,omitempty"`
	NewUsername     string                 `protobuf:"bytes,2,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	Client          string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Ip              string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUsernameReq) Reset() {
	*x = UpdateUsernameReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameReq) ProtoMessage() {}

func (x *UpdateUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameReq.ProtoReflect.Descriptor instead.
func (*UpdateUsernameReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateUsernameReq) GetCurrentUsername() string {
	if x != nil {
		return x.CurrentUsername
	}
	return ""
}

func (x *UpdateUsernameReq) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

func (x *UpdateUsernameReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *UpdateUsernameReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type UpdateUsernameRes struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StatusCode              int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Token                   string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EmailVerified           bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	UserId                  int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName                string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName               string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationStatus bool                   `protobuf:"varint,9,opt,name=email_verification_status,json=emailVerificationStatus,proto3" json:"email_verification_status,omitempty"`
	Error                   *Error                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	AccountId               string                 `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateUsernameRes) Reset() {
	*x = UpdateUsernameRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRes) ProtoMessage() {}

func (x *UpdateUsernameRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRes.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUsernameRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateUsernameRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateUsernameRes) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *UpdateUsernameRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUsernameRes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateUsernameRes) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUsernameRes) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUsernameRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUsernameRes) GetEmailVerificationStatus() bool {
	if x != nil {
		return x.EmailVerificationStatus
	}
	return false
}

func (x *UpdateUsernameRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UpdateUsernameRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdatePasswordWithPasswordReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	IpAddress       string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client          string                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePasswordWithPasswordReq) Reset() {
	*x = UpdatePasswordWithPasswordReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordWithPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordWithPasswordReq) ProtoMessage() {}

func (x *UpdatePasswordWithPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordWithPasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordWithPasswordReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{23}
}

func (x *UpdatePasswordWithPasswordReq) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *UpdatePasswordWithPasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdatePasswordWithPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *UpdatePasswordWithPasswordReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UpdatePasswordWithPasswordReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UpdatePasswordWithPasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordWithPasswordRes) Reset() {
	*x = UpdatePasswordWithPasswordRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordWithPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordWithPasswordRes) ProtoMessage() {}

func (x *UpdatePasswordWithPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordWithPasswordRes.ProtoReflect.Descriptor instead.
func (*UpdatePasswordWithPasswordRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePasswordWithPasswordRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdatePasswordWithPasswordRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateEmailIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewEmail      string                 `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailIdReq) Reset() {
	*x = UpdateEmailIdReq{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailIdReq) ProtoMessage() {}

func (x *UpdateEmailIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailIdReq.ProtoReflect.Descriptor instead.
func (*UpdateEmailIdReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateEmailIdReq) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

func (x *UpdateEmailIdReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UpdateEmailIdReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *UpdateEmailIdReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateEmailIdRes struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StatusCode              int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Token                   string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EmailVerified           bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	UserId                  int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName                string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName               string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                   string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationStatus bool                   `protobuf:"varint,9,opt,name=email_verification_status,json=emailVerificationStatus,proto3" json:"email_verification_status,omitempty"`
	Error                   *Error                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	AccountId               string                 `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateEmailIdRes) Reset() {
	*x = UpdateEmailIdRes{}
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailIdRes) ProtoMessage() {}

func (x *UpdateEmailIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailIdRes.ProtoReflect.Descriptor instead.
func (*UpdateEmailIdRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateEmailIdRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateEmailIdRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateEmailIdRes) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *UpdateEmailIdRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateEmailIdRes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateEmailIdRes) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateEmailIdRes) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateEmailIdRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmailIdRes) GetEmailVerificationStatus() bool {
	if x != nil {
		return x.EmailVerificationStatus
	}
	return false
}

func (x *UpdateEmailIdRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UpdateEmailIdRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_apis_serviceconn_gateway_authz_pb_gw_auth_proto protoreflect.FileDescriptor

const file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDesc = "" +
	"\n" +
	"/apis/serviceconn/gateway_authz/pb/gw_auth.proto\x12\bauth_svc\"\xd1\x02\n" +
	"\x13RegisterUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12L\n" +
	"\flogin_method\x18\x05 \x01(\x0e2).auth_svc.RegisterUserRequest.LoginMethodR\vloginMethod\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\a \x01(\tR\x06client\"G\n" +
	"\vLoginMethod\x12\x0f\n" +
	"\vThe_MONKEYS\x10\x00\x12\x0e\n" +
	"\n" +
	"GOOGLE_ACC\x10\x01\x12\v\n" +
	"\aANDROID\x10\x02\x12\n" +
	"\n" +
	"\x06IPHONE\x10\x03\"\xfd\x02\n" +
	"\x14RegisterUserResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12:\n" +
	"\x19email_verification_status\x18\t \x01(\tR\x17emailVerificationStatus\x12%\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountId\"O\n" +
	"\x05Error\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"s\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\"\xc5\x01\n" +
	"\x10ValidateResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12%\n" +
	"\x05error\x18\x05 \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\tR\taccountId\".\n" +
	"\x16DecodeSignedJWTRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xc3\x02\n" +
	"\x17DecodeSignedJWTResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12:\n" +
	"\x19email_verification_status\x18\a \x01(\tR\x17emailVerificationStatus\x12%\n" +
	"\x05error\x18\b \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\tR\taccountId\"\xae\x01\n" +
	"\x0eAccessCheckReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x17\n" +
	"\ablog_id\x18\x05 \x01(\tR\x06blogId\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\"\xef\x01\n" +
	"\x0eAccessCheckRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x16\n" +
	"\x06access\x18\x05 \x03(\tR\x06access\x12\x17\n" +
	"\ablog_id\x18\x06 \x01(\tR\x06blogId\x12%\n" +
	"\x05error\x18\a \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\"{\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\"\xfa\x02\n" +
	"\x11LoginUserResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12:\n" +
	"\x19email_verification_status\x18\t \x01(\tR\x17emailVerificationStatus\x12%\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountId\"`\n" +
	"\x11ForgotPasswordReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\"u\n" +
	"\x11ForgotPasswordRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.auth_svc.ErrorR\x05error\"\xa1\x01\n" +
	"\x10ResetPasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x06 \x01(\tR\x06client\"\xdb\x02\n" +
	"\x10ResetPasswordRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12:\n" +
	"\x19email_verification_status\x18\t \x01(\bR\x17emailVerificationStatus\x12%\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x0f.auth_svc.ErrorR\x05error\"\x98\x01\n" +
	"\x11UpdatePasswordReq\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x05 \x01(\tR\x06client\"[\n" +
	"\x11UpdatePasswordRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.auth_svc.ErrorR\x05error\"c\n" +
	"\x14EmailVerificationReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\"^\n" +
	"\x14EmailVerificationRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.auth_svc.ErrorR\x05error\"\x8f\x01\n" +
	"\x0eVerifyEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x05 \x01(\tR\x06client\"n\n" +
	"\x0eVerifyEmailRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x89\x01\n" +
	"\x11UpdateUsernameReq\x12)\n" +
	"\x10current_username\x18\x01 \x01(\tR\x0fcurrentUsername\x12!\n" +
	"\fnew_username\x18\x02 \x01(\tR\vnewUsername\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\"\xfb\x02\n" +
	"\x11UpdateUsernameRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12:\n" +
	"\x19email_verification_status\x18\t \x01(\bR\x17emailVerificationStatus\x12%\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountId\"\xc0\x01\n" +
	"\x1dUpdatePasswordWithPasswordReq\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x05 \x01(\tR\x06client\"g\n" +
	"\x1dUpdatePasswordWithPasswordRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.auth_svc.ErrorR\x05error\"\x82\x01\n" +
	"\x10UpdateEmailIdReq\x12\x1b\n" +
	"\tnew_email\x18\x01 \x01(\tR\bnewEmail\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"\xfa\x02\n" +
	"\x10UpdateEmailIdRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12:\n" +
	"\x19email_verification_status\x18\t \x01(\bR\x17emailVerificationStatus\x12%\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x0f.auth_svc.ErrorR\x05error\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountId2\xf3\b\n" +
	"\vAuthService\x12O\n" +
	"\fRegisterUser\x12\x1d.auth_svc.RegisterUserRequest\x1a\x1e.auth_svc.RegisterUserResponse\"\x00\x12C\n" +
	"\bValidate\x12\x19.auth_svc.ValidateRequest\x1a\x1a.auth_svc.ValidateResponse\"\x00\x12H\n" +
	"\x10CheckAccessLevel\x12\x18.auth_svc.AccessCheckReq\x1a\x18.auth_svc.AccessCheckRes\"\x00\x12B\n" +
	"\x05Login\x12\x1a.auth_svc.LoginUserRequest\x1a\x1b.auth_svc.LoginUserResponse\"\x00\x12L\n" +
	"\x0eForgotPassword\x12\x1b.auth_svc.ForgotPasswordReq\x1a\x1b.auth_svc.ForgotPasswordRes\"\x00\x12I\n" +
	"\rResetPassword\x12\x1a.auth_svc.ResetPasswordReq\x1a\x1a.auth_svc.ResetPasswordRes\"\x00\x12L\n" +
	"\x0eUpdatePassword\x12\x1b.auth_svc.UpdatePasswordReq\x1a\x1b.auth_svc.UpdatePasswordRes\"\x00\x12_\n" +
	"\x1bRequestForEmailVerification\x12\x1e.auth_svc.EmailVerificationReq\x1a\x1e.auth_svc.EmailVerificationRes\"\x00\x12C\n" +
	"\vVerifyEmail\x12\x18.auth_svc.VerifyEmailReq\x1a\x18.auth_svc.VerifyEmailRes\"\x00\x12L\n" +
	"\x0eUpdateUsername\x12\x1b.auth_svc.UpdateUsernameReq\x1a\x1b.auth_svc.UpdateUsernameRes\"\x00\x12p\n" +
	"\x1aUpdatePasswordWithPassword\x12'.auth_svc.UpdatePasswordWithPasswordReq\x1a'.auth_svc.UpdatePasswordWithPasswordRes\"\x00\x12I\n" +
	"\rUpdateEmailId\x12\x1a.auth_svc.UpdateEmailIdReq\x1a\x1a.auth_svc.UpdateEmailIdRes\"\x00\x12N\n" +
	"\vGoogleLogin\x12\x1d.auth_svc.RegisterUserRequest\x1a\x1e.auth_svc.RegisterUserResponse\"\x00\x12X\n" +
	"\x0fDecodeSignedJWT\x12 .auth_svc.DecodeSignedJWTRequest\x1a!.auth_svc.DecodeSignedJWTResponse\"\x00B%Z#./apis/serviceconn/gateway_authz/pbb\x06proto3"

var (
	file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescData []byte
)

func file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDesc), len(file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDesc)))
	})
	return file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDescData
}

var file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_goTypes = []any{
	(RegisterUserRequest_LoginMethod)(0),  // 0: auth_svc.RegisterUserRequest.LoginMethod
	(*RegisterUserRequest)(nil),           // 1: auth_svc.RegisterUserRequest
	(*RegisterUserResponse)(nil),          // 2: auth_svc.RegisterUserResponse
	(*Error)(nil),                         // 3: auth_svc.Error
	(*ValidateRequest)(nil),               // 4: auth_svc.ValidateRequest
	(*ValidateResponse)(nil),              // 5: auth_svc.ValidateResponse
	(*DecodeSignedJWTRequest)(nil),        // 6: auth_svc.DecodeSignedJWTRequest
	(*DecodeSignedJWTResponse)(nil),       // 7: auth_svc.DecodeSignedJWTResponse
	(*AccessCheckReq)(nil),                // 8: auth_svc.AccessCheckReq
	(*AccessCheckRes)(nil),                // 9: auth_svc.AccessCheckRes
	(*LoginUserRequest)(nil),              // 10: auth_svc.LoginUserRequest
	(*LoginUserResponse)(nil),             // 11: auth_svc.LoginUserResponse
	(*ForgotPasswordReq)(nil),             // 12: auth_svc.ForgotPasswordReq
	(*ForgotPasswordRes)(nil),             // 13: auth_svc.ForgotPasswordRes
	(*ResetPasswordReq)(nil),              // 14: auth_svc.ResetPasswordReq
	(*ResetPasswordRes)(nil),              // 15: auth_svc.ResetPasswordRes
	(*UpdatePasswordReq)(nil),             // 16: auth_svc.UpdatePasswordReq
	(*UpdatePasswordRes)(nil),             // 17: auth_svc.UpdatePasswordRes
	(*EmailVerificationReq)(nil),          // 18: auth_svc.EmailVerificationReq
	(*EmailVerificationRes)(nil),          // 19: auth_svc.EmailVerificationRes
	(*VerifyEmailReq)(nil),                // 20: auth_svc.VerifyEmailReq
	(*VerifyEmailRes)(nil),                // 21: auth_svc.VerifyEmailRes
	(*UpdateUsernameReq)(nil),             // 22: auth_svc.UpdateUsernameReq
	(*UpdateUsernameRes)(nil),             // 23: auth_svc.UpdateUsernameRes
	(*UpdatePasswordWithPasswordReq)(nil), // 24: auth_svc.UpdatePasswordWithPasswordReq
	(*UpdatePasswordWithPasswordRes)(nil), // 25: auth_svc.UpdatePasswordWithPasswordRes
	(*UpdateEmailIdReq)(nil),              // 26: auth_svc.UpdateEmailIdReq
	(*UpdateEmailIdRes)(nil),              // 27: auth_svc.UpdateEmailIdRes
}
var file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_depIdxs = []int32{
	0,  // 0: auth_svc.RegisterUserRequest.login_method:type_name -> auth_svc.RegisterUserRequest.LoginMethod
	3,  // 1: auth_svc.RegisterUserResponse.error:type_name -> auth_svc.Error
	3,  // 2: auth_svc.ValidateResponse.error:type_name -> auth_svc.Error
	3,  // 3: auth_svc.DecodeSignedJWTResponse.error:type_name -> auth_svc.Error
	3,  // 4: auth_svc.AccessCheckRes.error:type_name -> auth_svc.Error
	3,  // 5: auth_svc.LoginUserResponse.error:type_name -> auth_svc.Error
	3,  // 6: auth_svc.ForgotPasswordRes.error:type_name -> auth_svc.Error
	3,  // 7: auth_svc.ResetPasswordRes.error:type_name -> auth_svc.Error
	3,  // 8: auth_svc.UpdatePasswordRes.error:type_name -> auth_svc.Error
	3,  // 9: auth_svc.EmailVerificationRes.error:type_name -> auth_svc.Error
	3,  // 10: auth_svc.VerifyEmailRes.error:type_name -> auth_svc.Error
	3,  // 11: auth_svc.UpdateUsernameRes.error:type_name -> auth_svc.Error
	3,  // 12: auth_svc.UpdatePasswordWithPasswordRes.error:type_name -> auth_svc.Error
	3,  // 13: auth_svc.UpdateEmailIdRes.error:type_name -> auth_svc.Error
	1,  // 14: auth_svc.AuthService.RegisterUser:input_type -> auth_svc.RegisterUserRequest
	4,  // 15: auth_svc.AuthService.Validate:input_type -> auth_svc.ValidateRequest
	8,  // 16: auth_svc.AuthService.CheckAccessLevel:input_type -> auth_svc.AccessCheckReq
	10, // 17: auth_svc.AuthService.Login:input_type -> auth_svc.LoginUserRequest
	12, // 18: auth_svc.AuthService.ForgotPassword:input_type -> auth_svc.ForgotPasswordReq
	14, // 19: auth_svc.AuthService.ResetPassword:input_type -> auth_svc.ResetPasswordReq
	16, // 20: auth_svc.AuthService.UpdatePassword:input_type -> auth_svc.UpdatePasswordReq
	18, // 21: auth_svc.AuthService.RequestForEmailVerification:input_type -> auth_svc.EmailVerificationReq
	20, // 22: auth_svc.AuthService.VerifyEmail:input_type -> auth_svc.VerifyEmailReq
	22, // 23: auth_svc.AuthService.UpdateUsername:input_type -> auth_svc.UpdateUsernameReq
	24, // 24: auth_svc.AuthService.UpdatePasswordWithPassword:input_type -> auth_svc.UpdatePasswordWithPasswordReq
	26, // 25: auth_svc.AuthService.UpdateEmailId:input_type -> auth_svc.UpdateEmailIdReq
	1,  // 26: auth_svc.AuthService.GoogleLogin:input_type -> auth_svc.RegisterUserRequest
	6,  // 27: auth_svc.AuthService.DecodeSignedJWT:input_type -> auth_svc.DecodeSignedJWTRequest
	2,  // 28: auth_svc.AuthService.RegisterUser:output_type -> auth_svc.RegisterUserResponse
	5,  // 29: auth_svc.AuthService.Validate:output_type -> auth_svc.ValidateResponse
	9,  // 30: auth_svc.AuthService.CheckAccessLevel:output_type -> auth_svc.AccessCheckRes
	11, // 31: auth_svc.AuthService.Login:output_type -> auth_svc.LoginUserResponse
	13, // 32: auth_svc.AuthService.ForgotPassword:output_type -> auth_svc.ForgotPasswordRes
	15, // 33: auth_svc.AuthService.ResetPassword:output_type -> auth_svc.ResetPasswordRes
	17, // 34: auth_svc.AuthService.UpdatePassword:output_type -> auth_svc.UpdatePasswordRes
	19, // 35: auth_svc.AuthService.RequestForEmailVerification:output_type -> auth_svc.EmailVerificationRes
	21, // 36: auth_svc.AuthService.VerifyEmail:output_type -> auth_svc.VerifyEmailRes
	23, // 37: auth_svc.AuthService.UpdateUsername:output_type -> auth_svc.UpdateUsernameRes
	25, // 38: auth_svc.AuthService.UpdatePasswordWithPassword:output_type -> auth_svc.UpdatePasswordWithPasswordRes
	27, // 39: auth_svc.AuthService.UpdateEmailId:output_type -> auth_svc.UpdateEmailIdRes
	2,  // 40: auth_svc.AuthService.GoogleLogin:output_type -> auth_svc.RegisterUserResponse
	7,  // 41: auth_svc.AuthService.DecodeSignedJWT:output_type -> auth_svc.DecodeSignedJWTResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_init() }
func file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_init() {
	if File_apis_serviceconn_gateway_authz_pb_gw_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDesc), len(file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_depIdxs,
		EnumInfos:         file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_enumTypes,
		MessageInfos:      file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_authz_pb_gw_auth_proto = out.File
	file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_goTypes = nil
	file_apis_serviceconn_gateway_authz_pb_gw_auth_proto_depIdxs = nil
}
