swagger: "2.0"
info:
  title: The Monkeys
  version: 0.0.1
tags:
  - name: Auth Service
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/register:
    post:
      operationId: AuthService.register
      responses:
        "201":
          description: A successful response.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 201
              token:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.VlLhbI_kSO75W7Gi.4-VlLhbI_kSO75W7Gi-4GhUcNrqwKLIEukNDI"
              userId:
                type: integer
                example: 144
              userName:
                type: string
                example: coffeewithdave
              first_name:
                type: string
                example: "Dave"
              last_name:
                type: string
                example: "August"
              email:
                type: string
                example: "email@example.com"
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              first_name:
                type: string
                example: "Dave"
              last_name:
                type: string
                example: "Aug"
              email:
                type: string
                example: "email@example.com"
              password:
                type: string
                example: "ExamplePass"

      tags:
        - Access
  /auth/login:
    post:
      operationId: AuthService.login
      responses:
        "201":
          description: A successful response.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 201
              token:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.VlLhbI_kSO75W7Gi.4-VlLhbI_kSO75W7Gi-4GhUcNrqwKLIEukNDI"
              userId:
                type: integer
                example: 144
              userName:
                type: string
                example: coffeewithdave
              first_name:
                type: string
                example: "Dave"
              last_name:
                type: string
                example: "August"
              email:
                type: string
                example: "email@example.com"
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                example: "email@example.com"
              password:
                type: string
                example: "ExamplePass"

      tags:
        - Access
  /auth/is-authenticated:
    get:
      operationId: AuthService.UserAuthenticated
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties:
              schema: {}
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: Description for Header1
        - in: header
          name: user
          type: string
          required: true
          description: Description for Header2
      tags:
        - Is User authenticated
  /auth/forgot-pass:
    post:
      operationId: AuthService.ForgetPass
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                example: "email@example.com"
      tags:
        - Reset Password
  /auth/reset-password:
    get:
      operationId: Reset.Pass
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              token:
                type: string
                example: adnhdh2438ruy8webfsdb
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - name: user
          in: query
          required: true
          description: Username of the user
          type: string
        - name: evpw
          in: query
          required: true
          description: Reset password token
          type: string
      tags:
        - Reset Password

  /auth/update-password:
    post:
      operationId: Update.Passowrd
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              new_password:
                type: string
                example: "NewPass123"
      tags:
        - Reset Password
  /auth/req-email-verification:
    post:
      operationId: AuthService.ReqForEmailVerification
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: Description for Header1
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      tags:
        - Email Verification
  /auth/verify-email:
    get:
      operationId: AuthService.VerifyEmail
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              token:
                type: string
                example: adnhdh2438ruy8webfsdb
        default:
          description: An unexpected error response.
          schema: {}
      parameters:
        - name: user
          in: query
          required: true
          description: Username of the user
          type: string
        - name: evpw
          in: query
          required: true
          description: Reset password token
          type: string
      tags:
        - Email Verification
definitions: {}
