swagger: "2.0"
info:
  title: The Monkeys Blog Scheduling API
  description: API documentation for Blog Scheduling features
  version: 1.0.0
  contact:
    name: The Monkeys Team
basePath: /api/v2
tags:
  - name: Blog Scheduling
    description: Endpoints for scheduling, managing, and retrieving scheduled blogs
consumes:
  - application/json
produces:
  - application/json

paths:
  # Schedule a Blog
  /blog/{blog_id}/schedule_blog:
    post:
      tags:
        - Blog Scheduling
      summary: Schedule a blog
      description: Schedule a blog to be published at a future time
      operationId: scheduleBlog
      parameters:
        - name: blog_id
          in: path
          description: ID of the blog to schedule
          required: true
          type: string
        - name: body
          in: body
          description: Scheduling details including time, timezone, tags, and slug
          required: true
          schema:
            type: object
            required:
              - schedule_time
              - timezone
            properties:
              tags:
                type: array
                items:
                  type: string
                description: List of tags for the blog
                example: ["tech", "scheduler"]
              slug:
                type: string
                description: URL slug for the blog
                example: "my-scheduled-blog"
              schedule_time:
                type: string
                format: date-time
                description: RFC3339 timestamp for when to publish
                example: "2026-01-20T10:00:00Z"
              timezone:
                type: string
                description: User's timezone (e.g., "Asia/Kolkata")
                example: "Asia/Kolkata"
      responses:
        '200':
          description: Blog scheduled successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "the blog 123 has been scheduled for 2026-01-20T10:00:00Z!"
        '400':
          description: Invalid input or blog not found
        '500':
          description: Internal server error
      security:
        - Bearer: []

  # Get Scheduled Blogs
  /blog/my-scheduled_blog:
    get:
      tags:
        - Blog Scheduling
      summary: Get my scheduled blogs
      description: Retrieve all scheduled blogs for the authenticated user
      operationId: getMyScheduledBlogs
      responses:
        '200':
          description: List of scheduled blogs
          schema:
            type: object
            properties:
              blogs:
                type: array
                items:
                  $ref: '#/definitions/Blog'
        '500':
          description: Internal server error
      security:
        - Bearer: []

  # Delete Scheduled Blog
  /blog/{blog_id}/schedule:
    delete:
      tags:
        - Blog Scheduling
      summary: Delete a scheduled blog
      description: Permanently delete a scheduled blog
      operationId: deleteScheduledBlog
      parameters:
        - name: blog_id
          in: path
          description: ID of the scheduled blog to delete
          required: true
          type: string
      responses:
        '200':
          description: Scheduled blog deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "the scheduled blog 123 has been deleted!"
        '404':
          description: Blog not found
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - Bearer: []

  # Move Scheduled Blog to Draft
  /blog/{blog_id}/schedule/to-draft:
    post:
      tags:
        - Blog Scheduling
      summary: Move scheduled blog to draft
      description: Cancel the schedule and move the blog back to draft status
      operationId: moveScheduledBlogToDraft
      parameters:
        - name: blog_id
          in: path
          description: ID of the scheduled blog to move to draft
          required: true
          type: string
      responses:
        '200':
          description: Blog moved to draft successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "the scheduled blog 123 has been moved to draft!"
        '404':
          description: Blog not found
        '403':
          description: Unauthorized or blog not scheduled
        '500':
          description: Internal server error
      security:
        - Bearer: []

definitions:
  Blog:
    type: object
    properties:
      blog_id:
        type: string
      owner_account_id:
        type: string
      # Minified definition for referencing
      title:
        type: string
      is_schedule:
        type: boolean
      schedule_time:
        type: string
        format: date-time
      timezone:
        type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: JWT token prefixed with "Bearer "
