swagger: '2.0'
info:
  title: Blog Text Editor API
  version: '1.0'
host: themonkeys.tech
basePath: /api/v1
schemes:
  - https
paths:
  /files/post/{postId}:
    post:
      summary: Upload file from blog text editor
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: postId
          required: true
          type: string
        - in: header
          name: Authorization
          required: true
          type: string
        - in: formData
          name: file
          required: true
          type: file
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
              newFileName:
                type: string
      tags:
        - Blog Files
  /files/post/{postId}/{filename}:
    get:
      summary: Get file from blog text editor
      parameters:
        - in: path
          name: postId
          required: true
          type: string
        - in: path
          name: filename
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      tags:
        - Blog Files
    delete:
      summary: Delete a file
      parameters:
        - in: path
          name: postId
          required: true
          type: string
        - in: path
          name: filename
          required: true
          type: string
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              message:
                type: string
              status:
                type: integer
      tags:
        - Blog Files
  /files/profile/{userId}/profile:
    post:
      summary: Upload profile picture
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: userId
          required: true
          type: string
        - in: header
          name: Authorization
          required: true
          type: string
        - in: formData
          name: profile_pic
          required: true
          type: file
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
              file_name:
                type: string
      tags:
        - Profile pic
    get:
      summary: Get profile picture
      produces:
        - image/png
        - image/jpeg
        - image/gif
      parameters:
        - in: path
          name: userId
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: file
      tags:
          - Profile pic
    delete:
      summary: Delete profile picture
      parameters:
        - in: path
          name: userId
          required: true
          type: string
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              message:
                type: string
              status:
                type: integer
      tags:
          - Profile pic



