// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/serviceconn/gateway_user/pb/gw_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,6,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileReq) Reset() {
	*x = UserProfileReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileReq) ProtoMessage() {}

func (x *UserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileReq.ProtoReflect.Descriptor instead.
func (*UserProfileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserProfileReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfileReq) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *UserProfileReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserProfileReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	RoleId        int64                  `protobuf:"varint,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Address       string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	ContactNumber string                 `protobuf:"bytes,12,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	UserStatus    string                 `protobuf:"bytes,13,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	Instagram     string                 `protobuf:"bytes,14,opt,name=instagram,proto3" json:"instagram,omitempty"`
	Linkedin      string                 `protobuf:"bytes,15,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Twitter       string                 `protobuf:"bytes,16,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Github        string                 `protobuf:"bytes,17,opt,name=github,proto3" json:"github,omitempty"`
	Topics        []string               `protobuf:"bytes,18,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileRes) Reset() {
	*x = UserProfileRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileRes) ProtoMessage() {}

func (x *UserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileRes.ProtoReflect.Descriptor instead.
func (*UserProfileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfileRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserProfileRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileRes) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfileRes) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfileRes) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UserProfileRes) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserProfileRes) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfileRes) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfileRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfileRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserProfileRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserProfileRes) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *UserProfileRes) GetUserStatus() string {
	if x != nil {
		return x.UserStatus
	}
	return ""
}

func (x *UserProfileRes) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *UserProfileRes) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *UserProfileRes) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

func (x *UserProfileRes) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *UserProfileRes) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type UserActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivityReq) Reset() {
	*x = UserActivityReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivityReq) ProtoMessage() {}

func (x *UserActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivityReq.ProtoReflect.Descriptor instead.
func (*UserActivityReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserActivityReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActivityReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserActivityReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserActivityReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserActivityReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UserActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []*UserActivity        `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivityResp) Reset() {
	*x = UserActivityResp{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivityResp) ProtoMessage() {}

func (x *UserActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivityResp.ProtoReflect.Descriptor instead.
func (*UserActivityResp) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserActivityResp) GetResponse() []*UserActivity {
	if x != nil {
		return x.Response
	}
	return nil
}

type UserActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ServiceType   string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserActivity) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UserActivity) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *UserActivity) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *UserActivity) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	ContactNumber string                 `protobuf:"bytes,7,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,9,opt,name=client,proto3" json:"client,omitempty"`
	Partial       bool                   `protobuf:"varint,10,opt,name=partial,proto3" json:"partial,omitempty"`
	Instagram     string                 `protobuf:"bytes,11,opt,name=instagram,proto3" json:"instagram,omitempty"`
	Linkedin      string                 `protobuf:"bytes,12,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Twitter       string                 `protobuf:"bytes,13,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Github        string                 `protobuf:"bytes,14,opt,name=github,proto3" json:"github,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileReq) Reset() {
	*x = UpdateUserProfileReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileReq) ProtoMessage() {}

func (x *UpdateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserProfileReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserProfileReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserProfileReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserProfileReq) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateUserProfileReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserProfileReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateUserProfileReq) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

func (x *UpdateUserProfileReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UpdateUserProfileReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *UpdateUserProfileReq) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *UpdateUserProfileReq) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *UpdateUserProfileReq) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *UpdateUserProfileReq) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

func (x *UpdateUserProfileReq) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

type UpdateUserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	ContactNumber int64                  `protobuf:"varint,8,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	Status        int64                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRes) Reset() {
	*x = UpdateUserProfileRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRes) ProtoMessage() {}

func (x *UpdateUserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRes.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserProfileRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateUserProfileRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserProfileRes) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserProfileRes) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserProfileRes) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateUserProfileRes) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserProfileRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateUserProfileRes) GetContactNumber() int64 {
	if x != nil {
		return x.ContactNumber
	}
	return 0
}

func (x *UpdateUserProfileRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserProfileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserProfileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProfileReq) Reset() {
	*x = DeleteUserProfileReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProfileReq) ProtoMessage() {}

func (x *DeleteUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProfileReq.ProtoReflect.Descriptor instead.
func (*DeleteUserProfileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserProfileReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeleteUserProfileReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeleteUserProfileReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeleteUserProfileReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *DeleteUserProfileReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type DeleteUserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserProfileRes) Reset() {
	*x = DeleteUserProfileRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserProfileRes) ProtoMessage() {}

func (x *DeleteUserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserProfileRes.ProtoReflect.Descriptor instead.
func (*DeleteUserProfileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserProfileRes) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *DeleteUserProfileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteUserProfileRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTopicsRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsRequests) Reset() {
	*x = GetTopicsRequests{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsRequests) ProtoMessage() {}

func (x *GetTopicsRequests) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsRequests.ProtoReflect.Descriptor instead.
func (*GetTopicsRequests) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{9}
}

type Topics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topics) Reset() {
	*x = Topics{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topics) ProtoMessage() {}

func (x *Topics) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topics.ProtoReflect.Descriptor instead.
func (*Topics) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{10}
}

func (x *Topics) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Topics) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topics              `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsResponse) Reset() {
	*x = GetTopicsResponse{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsResponse) ProtoMessage() {}

func (x *GetTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetTopicsResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetTopicsResponse) GetTopics() []*Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{12}
}

func (x *Category) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetAllCategoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCategoriesReq) Reset() {
	*x = GetAllCategoriesReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCategoriesReq) ProtoMessage() {}

func (x *GetAllCategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCategoriesReq.ProtoReflect.Descriptor instead.
func (*GetAllCategoriesReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{13}
}

type GetAllCategoriesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      map[string]*Category   `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCategoriesRes) Reset() {
	*x = GetAllCategoriesRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCategoriesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCategoriesRes) ProtoMessage() {}

func (x *GetAllCategoriesRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCategoriesRes.ProtoReflect.Descriptor instead.
func (*GetAllCategoriesRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllCategoriesRes) GetCategory() map[string]*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type UserDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,4,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailReq) Reset() {
	*x = UserDetailReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailReq) ProtoMessage() {}

func (x *UserDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailReq.ProtoReflect.Descriptor instead.
func (*UserDetailReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserDetailReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserDetailReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDetailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetailReq) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *UserDetailReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UserDetailReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UserDetailsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailsResp) Reset() {
	*x = UserDetailsResp{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailsResp) ProtoMessage() {}

func (x *UserDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailsResp.ProtoReflect.Descriptor instead.
func (*UserDetailsResp) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserDetailsResp) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserDetailsResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDetailsResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserDetailsResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserDetailsResp) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserDetailsResp) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserDetailsResp) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserDetailsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TopicActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         []string               `protobuf:"bytes,1,rep,name=topic,proto3" json:"topic,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicActionReq) Reset() {
	*x = TopicActionReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicActionReq) ProtoMessage() {}

func (x *TopicActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicActionReq.ProtoReflect.Descriptor instead.
func (*TopicActionReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{17}
}

func (x *TopicActionReq) GetTopic() []string {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *TopicActionReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TopicActionReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TopicActionReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type TopicActionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicActionRes) Reset() {
	*x = TopicActionRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicActionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicActionRes) ProtoMessage() {}

func (x *TopicActionRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicActionRes.ProtoReflect.Descriptor instead.
func (*TopicActionRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{18}
}

func (x *TopicActionRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TopicActionRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TopicActionRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CoAuthorAccessReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Ip                string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Client            string                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	BlogOwnerUsername string                 `protobuf:"bytes,6,opt,name=blog_owner_username,json=blogOwnerUsername,proto3" json:"blog_owner_username,omitempty"`
	BlogId            string                 `protobuf:"bytes,7,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CoAuthorAccessReq) Reset() {
	*x = CoAuthorAccessReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoAuthorAccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoAuthorAccessReq) ProtoMessage() {}

func (x *CoAuthorAccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoAuthorAccessReq.ProtoReflect.Descriptor instead.
func (*CoAuthorAccessReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{19}
}

func (x *CoAuthorAccessReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CoAuthorAccessReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CoAuthorAccessReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CoAuthorAccessReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CoAuthorAccessReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *CoAuthorAccessReq) GetBlogOwnerUsername() string {
	if x != nil {
		return x.BlogOwnerUsername
	}
	return ""
}

func (x *CoAuthorAccessReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type CoAuthorAccessRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoAuthorAccessRes) Reset() {
	*x = CoAuthorAccessRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoAuthorAccessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoAuthorAccessRes) ProtoMessage() {}

func (x *CoAuthorAccessRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoAuthorAccessRes.ProtoReflect.Descriptor instead.
func (*CoAuthorAccessRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{20}
}

func (x *CoAuthorAccessRes) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CoAuthorAccessRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CoAuthorAccessRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CoAuthorAccessRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CoAuthorAccessRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CoAuthorAccessRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BlogsByUserIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogsByUserIdsReq) Reset() {
	*x = BlogsByUserIdsReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogsByUserIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogsByUserIdsReq) ProtoMessage() {}

func (x *BlogsByUserIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogsByUserIdsReq.ProtoReflect.Descriptor instead.
func (*BlogsByUserIdsReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{21}
}

func (x *BlogsByUserIdsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BlogsByUserIdsReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlogsByUserIdsReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Blog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BlogId        string                 `protobuf:"bytes,4,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Permission    string                 `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{22}
}

func (x *Blog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Blog) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Blog) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *Blog) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Blog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BlogsByUserNameRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*Blog                `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogsByUserNameRes) Reset() {
	*x = BlogsByUserNameRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogsByUserNameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogsByUserNameRes) ProtoMessage() {}

func (x *BlogsByUserNameRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogsByUserNameRes.ProtoReflect.Descriptor instead.
func (*BlogsByUserNameRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{23}
}

func (x *BlogsByUserNameRes) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type CreateTopicsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicsReq) Reset() {
	*x = CreateTopicsReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicsReq) ProtoMessage() {}

func (x *CreateTopicsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicsReq.ProtoReflect.Descriptor instead.
func (*CreateTopicsReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTopicsReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *CreateTopicsReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTopicsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateTopicsReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CreateTopicsReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type CreateTopicsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicsRes) Reset() {
	*x = CreateTopicsRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicsRes) ProtoMessage() {}

func (x *CreateTopicsRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicsRes.ProtoReflect.Descriptor instead.
func (*CreateTopicsRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{25}
}

func (x *CreateTopicsRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTopicsRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTopicsRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BookMarkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookMarkReq) Reset() {
	*x = BookMarkReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookMarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookMarkReq) ProtoMessage() {}

func (x *BookMarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookMarkReq.ProtoReflect.Descriptor instead.
func (*BookMarkReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{26}
}

func (x *BookMarkReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *BookMarkReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BookMarkReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BookMarkReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type BookMarkRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	IsLiked       bool                   `protobuf:"varint,4,opt,name=isLiked,proto3" json:"isLiked,omitempty"`
	BookMarked    bool                   `protobuf:"varint,5,opt,name=bookMarked,proto3" json:"bookMarked,omitempty"`
	BlogIds       []string               `protobuf:"bytes,6,rep,name=blog_ids,json=blogIds,proto3" json:"blog_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookMarkRes) Reset() {
	*x = BookMarkRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookMarkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookMarkRes) ProtoMessage() {}

func (x *BookMarkRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookMarkRes.ProtoReflect.Descriptor instead.
func (*BookMarkRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{27}
}

func (x *BookMarkRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BookMarkRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BookMarkRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BookMarkRes) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *BookMarkRes) GetBookMarked() bool {
	if x != nil {
		return x.BookMarked
	}
	return false
}

func (x *BookMarkRes) GetBlogIds() []string {
	if x != nil {
		return x.BlogIds
	}
	return nil
}

type UserFollowReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FollowerUsername string                 `protobuf:"bytes,2,opt,name=follower_username,json=followerUsername,proto3" json:"follower_username,omitempty"`
	Ip               string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Client           string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserFollowReq) Reset() {
	*x = UserFollowReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowReq) ProtoMessage() {}

func (x *UserFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollowReq.ProtoReflect.Descriptor instead.
func (*UserFollowReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{28}
}

func (x *UserFollowReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserFollowReq) GetFollowerUsername() string {
	if x != nil {
		return x.FollowerUsername
	}
	return ""
}

func (x *UserFollowReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserFollowReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UserFollowRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,4,opt,name=isFollowing,proto3" json:"isFollowing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFollowRes) Reset() {
	*x = UserFollowRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollowRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowRes) ProtoMessage() {}

func (x *UserFollowRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollowRes.ProtoReflect.Descriptor instead.
func (*UserFollowRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{29}
}

func (x *UserFollowRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserFollowRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserFollowRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UserFollowRes) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{30}
}

func (x *User) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type FollowerFollowingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerFollowingResp) Reset() {
	*x = FollowerFollowingResp{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerFollowingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerFollowingResp) ProtoMessage() {}

func (x *FollowerFollowingResp) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerFollowingResp.ProtoReflect.Descriptor instead.
func (*FollowerFollowingResp) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{31}
}

func (x *FollowerFollowingResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FollowerFollowingResp) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FollowerFollowingResp) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResp) Reset() {
	*x = CountResp{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResp) ProtoMessage() {}

func (x *CountResp) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResp.ProtoReflect.Descriptor instead.
func (*CountResp) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{32}
}

func (x *CountResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CountResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CountResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FollowerFollowingCountsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     int64                  `protobuf:"varint,1,opt,name=followers,proto3" json:"followers,omitempty"`
	Following     int64                  `protobuf:"varint,2,opt,name=following,proto3" json:"following,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerFollowingCountsResp) Reset() {
	*x = FollowerFollowingCountsResp{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerFollowingCountsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerFollowingCountsResp) ProtoMessage() {}

func (x *FollowerFollowingCountsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerFollowingCountsResp.ProtoReflect.Descriptor instead.
func (*FollowerFollowingCountsResp) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{33}
}

func (x *FollowerFollowingCountsResp) GetFollowers() int64 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *FollowerFollowingCountsResp) GetFollowing() int64 {
	if x != nil {
		return x.Following
	}
	return 0
}

func (x *FollowerFollowingCountsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FollowerFollowingCountsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FollowerFollowingCountsResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetBatchUserDetailsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchUserDetailsReq) Reset() {
	*x = GetBatchUserDetailsReq{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchUserDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchUserDetailsReq) ProtoMessage() {}

func (x *GetBatchUserDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchUserDetailsReq.ProtoReflect.Descriptor instead.
func (*GetBatchUserDetailsReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{34}
}

func (x *GetBatchUserDetailsReq) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

type GetBatchUserDetailsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserDetailsResp     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchUserDetailsRes) Reset() {
	*x = GetBatchUserDetailsRes{}
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchUserDetailsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchUserDetailsRes) ProtoMessage() {}

func (x *GetBatchUserDetailsRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchUserDetailsRes.ProtoReflect.Descriptor instead.
func (*GetBatchUserDetailsRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{35}
}

func (x *GetBatchUserDetailsRes) GetUsers() []*UserDetailsResp {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_apis_serviceconn_gateway_user_pb_gw_user_proto protoreflect.FileDescriptor

const file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc = "" +
	"\n" +
	".apis/serviceconn/gateway_user/pb/gw_user.proto\x12\bauth_svc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\x0eUserProfileReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x06 \x01(\tR\x06client\"\xd1\x04\n" +
	"\x0eUserProfileRes\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x05 \x01(\tR\vdateOfBirth\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\x03R\x06roleId\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12%\n" +
	"\x0econtact_number\x18\f \x01(\tR\rcontactNumber\x12\x1f\n" +
	"\vuser_status\x18\r \x01(\tR\n" +
	"userStatus\x12\x1c\n" +
	"\tinstagram\x18\x0e \x01(\tR\tinstagram\x12\x1a\n" +
	"\blinkedin\x18\x0f \x01(\tR\blinkedin\x12\x18\n" +
	"\atwitter\x18\x10 \x01(\tR\atwitter\x12\x16\n" +
	"\x06github\x18\x11 \x01(\tR\x06github\x12\x16\n" +
	"\x06topics\x18\x12 \x03(\tR\x06topics\"\x85\x01\n" +
	"\x0fUserActivityReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x05 \x01(\tR\x06client\"F\n" +
	"\x10UserActivityResp\x122\n" +
	"\bresponse\x18\x01 \x03(\v2\x16.auth_svc.UserActivityR\bresponse\"\xaf\x01\n" +
	"\fUserActivity\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12!\n" +
	"\fservice_type\x18\x02 \x01(\tR\vserviceType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x93\x03\n" +
	"\x14UpdateUserProfileReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12%\n" +
	"\x0econtact_number\x18\a \x01(\tR\rcontactNumber\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\t \x01(\tR\x06client\x12\x18\n" +
	"\apartial\x18\n" +
	" \x01(\bR\apartial\x12\x1c\n" +
	"\tinstagram\x18\v \x01(\tR\tinstagram\x12\x1a\n" +
	"\blinkedin\x18\f \x01(\tR\blinkedin\x12\x18\n" +
	"\atwitter\x18\r \x01(\tR\atwitter\x12\x16\n" +
	"\x06github\x18\x0e \x01(\tR\x06github\"\xc8\x02\n" +
	"\x14UpdateUserProfileRes\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x05 \x01(\tR\vdateOfBirth\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12%\n" +
	"\x0econtact_number\x18\b \x01(\x03R\rcontactNumber\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\"\x8f\x01\n" +
	"\x14DeleteUserProfileReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\"^\n" +
	"\x14DeleteUserProfileRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x13\n" +
	"\x11GetTopicsRequests\":\n" +
	"\x06Topics\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"=\n" +
	"\x11GetTopicsResponse\x12(\n" +
	"\x06topics\x18\x01 \x03(\v2\x10.auth_svc.TopicsR\x06topics\"\"\n" +
	"\bCategory\x12\x16\n" +
	"\x06Topics\x18\x01 \x03(\tR\x06Topics\"\x15\n" +
	"\x13GetAllCategoriesReq\"\xaf\x01\n" +
	"\x13GetAllCategoriesRes\x12G\n" +
	"\bcategory\x18\x01 \x03(\v2+.auth_svc.GetAllCategoriesRes.CategoryEntryR\bcategory\x1aO\n" +
	"\rCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.auth_svc.CategoryR\x05value:\x028\x01\"\xaf\x01\n" +
	"\rUserDetailReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vsearch_term\x18\x04 \x01(\tR\n" +
	"searchTerm\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\xeb\x01\n" +
	"\x0fUserDetailsResp\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"j\n" +
	"\x0eTopicActionReq\x12\x14\n" +
	"\x05topic\x18\x01 \x03(\tR\x05topic\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\"X\n" +
	"\x0eTopicActionRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd5\x01\n" +
	"\x11CoAuthorAccessReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x05 \x01(\tR\x06client\x12.\n" +
	"\x13blog_owner_username\x18\x06 \x01(\tR\x11blogOwnerUsername\x12\x17\n" +
	"\ablog_id\x18\a \x01(\tR\x06blogId\"\xac\x01\n" +
	"\x11CoAuthorAccessRes\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"b\n" +
	"\x11BlogsByUserIdsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"\xa2\x01\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x17\n" +
	"\ablog_id\x18\x04 \x01(\tR\x06blogId\x12\x1e\n" +
	"\n" +
	"permission\x18\x05 \x01(\tR\n" +
	"permission\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\":\n" +
	"\x12BlogsByUserNameRes\x12$\n" +
	"\x05blogs\x18\x01 \x03(\v2\x0e.auth_svc.BlogR\x05blogs\"\x89\x01\n" +
	"\x0fCreateTopicsReq\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x05 \x01(\tR\x06client\"Y\n" +
	"\x0fCreateTopicsRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"j\n" +
	"\vBookMarkReq\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\"\xaa\x01\n" +
	"\vBookMarkRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aisLiked\x18\x04 \x01(\bR\aisLiked\x12\x1e\n" +
	"\n" +
	"bookMarked\x18\x05 \x01(\bR\n" +
	"bookMarked\x12\x19\n" +
	"\bblog_ids\x18\x06 \x03(\tR\ablogIds\"\x80\x01\n" +
	"\rUserFollowReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12+\n" +
	"\x11follower_username\x18\x02 \x01(\tR\x10followerUsername\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\"y\n" +
	"\rUserFollowRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12 \n" +
	"\visFollowing\x18\x04 \x01(\bR\visFollowing\"\xc4\x01\n" +
	"\x04User\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\"k\n" +
	"\x15FollowerFollowingResp\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.auth_svc.UserR\x05users\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"O\n" +
	"\tCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xa1\x01\n" +
	"\x1bFollowerFollowingCountsResp\x12\x1c\n" +
	"\tfollowers\x18\x01 \x01(\x03R\tfollowers\x12\x1c\n" +
	"\tfollowing\x18\x02 \x01(\x03R\tfollowing\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"9\n" +
	"\x16GetBatchUserDetailsReq\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\"I\n" +
	"\x16GetBatchUserDetailsRes\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.auth_svc.UserDetailsRespR\x05users2\xc1\x11\n" +
	"\vUserService\x12L\n" +
	"\x11GetUserActivities\x12\x19.auth_svc.UserActivityReq\x1a\x1a.auth_svc.UserActivityResp\"\x00\x12F\n" +
	"\x0eGetUserProfile\x12\x18.auth_svc.UserProfileReq\x1a\x18.auth_svc.UserProfileRes\"\x00\x12U\n" +
	"\x11UpdateUserProfile\x12\x1e.auth_svc.UpdateUserProfileReq\x1a\x1e.auth_svc.UpdateUserProfileRes\"\x00\x12U\n" +
	"\x11DeleteUserAccount\x12\x1e.auth_svc.DeleteUserProfileReq\x1a\x1e.auth_svc.DeleteUserProfileRes\"\x00\x12J\n" +
	"\fGetAllTopics\x12\x1b.auth_svc.GetTopicsRequests\x1a\x1b.auth_svc.GetTopicsResponse\"\x00\x12R\n" +
	"\x10GetAllCategories\x12\x1d.auth_svc.GetAllCategoriesReq\x1a\x1d.auth_svc.GetAllCategoriesRes\"\x00\x12F\n" +
	"\x0eGetUserDetails\x12\x17.auth_svc.UserDetailReq\x1a\x19.auth_svc.UserDetailsResp\"\x00\x12D\n" +
	"\fFollowTopics\x12\x18.auth_svc.TopicActionReq\x1a\x18.auth_svc.TopicActionRes\"\x00\x12F\n" +
	"\x0eUnFollowTopics\x12\x18.auth_svc.TopicActionReq\x1a\x18.auth_svc.TopicActionRes\"\x00\x12@\n" +
	"\n" +
	"FollowUser\x12\x17.auth_svc.UserFollowReq\x1a\x17.auth_svc.UserFollowRes\"\x00\x12B\n" +
	"\fUnFollowUser\x12\x17.auth_svc.UserFollowReq\x1a\x17.auth_svc.UserFollowRes\"\x00\x12J\n" +
	"\fGetFollowers\x12\x17.auth_svc.UserDetailReq\x1a\x1f.auth_svc.FollowerFollowingResp\"\x00\x12J\n" +
	"\fGetFollowing\x12\x17.auth_svc.UserDetailReq\x1a\x1f.auth_svc.FollowerFollowingResp\"\x00\x12H\n" +
	"\x12GetIfIFollowedUser\x12\x17.auth_svc.UserFollowReq\x1a\x17.auth_svc.UserFollowRes\"\x00\x12_\n" +
	"\x1bGetFollowersFollowingCounts\x12\x17.auth_svc.UserDetailReq\x1a%.auth_svc.FollowerFollowingCountsResp\"\x00\x12L\n" +
	"\n" +
	"SearchUser\x12\x17.auth_svc.UserDetailReq\x1a\x1f.auth_svc.FollowerFollowingResp\"\x00(\x010\x01\x12>\n" +
	"\fBookMarkBlog\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12>\n" +
	"\fGetBookMarks\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12@\n" +
	"\x0eRemoveBookMark\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12:\n" +
	"\bLikeBlog\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12<\n" +
	"\n" +
	"UnlikeBlog\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12@\n" +
	"\x0eGetIfBlogLiked\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12E\n" +
	"\x13GetIfBlogBookMarked\x12\x15.auth_svc.BookMarkReq\x1a\x15.auth_svc.BookMarkRes\"\x00\x12A\n" +
	"\x11GetBookMarkCounts\x12\x15.auth_svc.BookMarkReq\x1a\x13.auth_svc.CountResp\"\x00\x12=\n" +
	"\rGetLikeCounts\x12\x15.auth_svc.BookMarkReq\x1a\x13.auth_svc.CountResp\"\x00\x12L\n" +
	"\x0eInviteCoAuthor\x12\x1b.auth_svc.CoAuthorAccessReq\x1a\x1b.auth_svc.CoAuthorAccessRes\"\x00\x12R\n" +
	"\x14RevokeCoAuthorAccess\x12\x1b.auth_svc.CoAuthorAccessReq\x1a\x1b.auth_svc.CoAuthorAccessRes\"\x00\x12P\n" +
	"\x11GetBlogsByUserIds\x12\x1b.auth_svc.BlogsByUserIdsReq\x1a\x1c.auth_svc.BlogsByUserNameRes\"\x00\x12I\n" +
	"\x0fCreateNewTopics\x12\x19.auth_svc.CreateTopicsReq\x1a\x19.auth_svc.CreateTopicsRes\"\x00\x12[\n" +
	"\x13GetBatchUserDetails\x12 .auth_svc.GetBatchUserDetailsReq\x1a .auth_svc.GetBatchUserDetailsRes\"\x00B$Z\"./apis/serviceconn/gateway_user/pbb\x06proto3"

var (
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData []byte
)

func file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc), len(file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc)))
	})
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData
}

var file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_apis_serviceconn_gateway_user_pb_gw_user_proto_goTypes = []any{
	(*UserProfileReq)(nil),              // 0: auth_svc.UserProfileReq
	(*UserProfileRes)(nil),              // 1: auth_svc.UserProfileRes
	(*UserActivityReq)(nil),             // 2: auth_svc.UserActivityReq
	(*UserActivityResp)(nil),            // 3: auth_svc.UserActivityResp
	(*UserActivity)(nil),                // 4: auth_svc.UserActivity
	(*UpdateUserProfileReq)(nil),        // 5: auth_svc.UpdateUserProfileReq
	(*UpdateUserProfileRes)(nil),        // 6: auth_svc.UpdateUserProfileRes
	(*DeleteUserProfileReq)(nil),        // 7: auth_svc.DeleteUserProfileReq
	(*DeleteUserProfileRes)(nil),        // 8: auth_svc.DeleteUserProfileRes
	(*GetTopicsRequests)(nil),           // 9: auth_svc.GetTopicsRequests
	(*Topics)(nil),                      // 10: auth_svc.Topics
	(*GetTopicsResponse)(nil),           // 11: auth_svc.GetTopicsResponse
	(*Category)(nil),                    // 12: auth_svc.Category
	(*GetAllCategoriesReq)(nil),         // 13: auth_svc.GetAllCategoriesReq
	(*GetAllCategoriesRes)(nil),         // 14: auth_svc.GetAllCategoriesRes
	(*UserDetailReq)(nil),               // 15: auth_svc.UserDetailReq
	(*UserDetailsResp)(nil),             // 16: auth_svc.UserDetailsResp
	(*TopicActionReq)(nil),              // 17: auth_svc.TopicActionReq
	(*TopicActionRes)(nil),              // 18: auth_svc.TopicActionRes
	(*CoAuthorAccessReq)(nil),           // 19: auth_svc.CoAuthorAccessReq
	(*CoAuthorAccessRes)(nil),           // 20: auth_svc.CoAuthorAccessRes
	(*BlogsByUserIdsReq)(nil),           // 21: auth_svc.BlogsByUserIdsReq
	(*Blog)(nil),                        // 22: auth_svc.Blog
	(*BlogsByUserNameRes)(nil),          // 23: auth_svc.BlogsByUserNameRes
	(*CreateTopicsReq)(nil),             // 24: auth_svc.CreateTopicsReq
	(*CreateTopicsRes)(nil),             // 25: auth_svc.CreateTopicsRes
	(*BookMarkReq)(nil),                 // 26: auth_svc.BookMarkReq
	(*BookMarkRes)(nil),                 // 27: auth_svc.BookMarkRes
	(*UserFollowReq)(nil),               // 28: auth_svc.UserFollowReq
	(*UserFollowRes)(nil),               // 29: auth_svc.UserFollowRes
	(*User)(nil),                        // 30: auth_svc.User
	(*FollowerFollowingResp)(nil),       // 31: auth_svc.FollowerFollowingResp
	(*CountResp)(nil),                   // 32: auth_svc.CountResp
	(*FollowerFollowingCountsResp)(nil), // 33: auth_svc.FollowerFollowingCountsResp
	(*GetBatchUserDetailsReq)(nil),      // 34: auth_svc.GetBatchUserDetailsReq
	(*GetBatchUserDetailsRes)(nil),      // 35: auth_svc.GetBatchUserDetailsRes
	nil,                                 // 36: auth_svc.GetAllCategoriesRes.CategoryEntry
	(*timestamppb.Timestamp)(nil),       // 37: google.protobuf.Timestamp
}
var file_apis_serviceconn_gateway_user_pb_gw_user_proto_depIdxs = []int32{
	37, // 0: auth_svc.UserProfileRes.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: auth_svc.UserProfileRes.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 2: auth_svc.UserActivityResp.response:type_name -> auth_svc.UserActivity
	10, // 3: auth_svc.GetTopicsResponse.topics:type_name -> auth_svc.Topics
	36, // 4: auth_svc.GetAllCategoriesRes.category:type_name -> auth_svc.GetAllCategoriesRes.CategoryEntry
	22, // 5: auth_svc.BlogsByUserNameRes.blogs:type_name -> auth_svc.Blog
	30, // 6: auth_svc.FollowerFollowingResp.users:type_name -> auth_svc.User
	16, // 7: auth_svc.GetBatchUserDetailsRes.users:type_name -> auth_svc.UserDetailsResp
	12, // 8: auth_svc.GetAllCategoriesRes.CategoryEntry.value:type_name -> auth_svc.Category
	2,  // 9: auth_svc.UserService.GetUserActivities:input_type -> auth_svc.UserActivityReq
	0,  // 10: auth_svc.UserService.GetUserProfile:input_type -> auth_svc.UserProfileReq
	5,  // 11: auth_svc.UserService.UpdateUserProfile:input_type -> auth_svc.UpdateUserProfileReq
	7,  // 12: auth_svc.UserService.DeleteUserAccount:input_type -> auth_svc.DeleteUserProfileReq
	9,  // 13: auth_svc.UserService.GetAllTopics:input_type -> auth_svc.GetTopicsRequests
	13, // 14: auth_svc.UserService.GetAllCategories:input_type -> auth_svc.GetAllCategoriesReq
	15, // 15: auth_svc.UserService.GetUserDetails:input_type -> auth_svc.UserDetailReq
	17, // 16: auth_svc.UserService.FollowTopics:input_type -> auth_svc.TopicActionReq
	17, // 17: auth_svc.UserService.UnFollowTopics:input_type -> auth_svc.TopicActionReq
	28, // 18: auth_svc.UserService.FollowUser:input_type -> auth_svc.UserFollowReq
	28, // 19: auth_svc.UserService.UnFollowUser:input_type -> auth_svc.UserFollowReq
	15, // 20: auth_svc.UserService.GetFollowers:input_type -> auth_svc.UserDetailReq
	15, // 21: auth_svc.UserService.GetFollowing:input_type -> auth_svc.UserDetailReq
	28, // 22: auth_svc.UserService.GetIfIFollowedUser:input_type -> auth_svc.UserFollowReq
	15, // 23: auth_svc.UserService.GetFollowersFollowingCounts:input_type -> auth_svc.UserDetailReq
	15, // 24: auth_svc.UserService.SearchUser:input_type -> auth_svc.UserDetailReq
	26, // 25: auth_svc.UserService.BookMarkBlog:input_type -> auth_svc.BookMarkReq
	26, // 26: auth_svc.UserService.GetBookMarks:input_type -> auth_svc.BookMarkReq
	26, // 27: auth_svc.UserService.RemoveBookMark:input_type -> auth_svc.BookMarkReq
	26, // 28: auth_svc.UserService.LikeBlog:input_type -> auth_svc.BookMarkReq
	26, // 29: auth_svc.UserService.UnlikeBlog:input_type -> auth_svc.BookMarkReq
	26, // 30: auth_svc.UserService.GetIfBlogLiked:input_type -> auth_svc.BookMarkReq
	26, // 31: auth_svc.UserService.GetIfBlogBookMarked:input_type -> auth_svc.BookMarkReq
	26, // 32: auth_svc.UserService.GetBookMarkCounts:input_type -> auth_svc.BookMarkReq
	26, // 33: auth_svc.UserService.GetLikeCounts:input_type -> auth_svc.BookMarkReq
	19, // 34: auth_svc.UserService.InviteCoAuthor:input_type -> auth_svc.CoAuthorAccessReq
	19, // 35: auth_svc.UserService.RevokeCoAuthorAccess:input_type -> auth_svc.CoAuthorAccessReq
	21, // 36: auth_svc.UserService.GetBlogsByUserIds:input_type -> auth_svc.BlogsByUserIdsReq
	24, // 37: auth_svc.UserService.CreateNewTopics:input_type -> auth_svc.CreateTopicsReq
	34, // 38: auth_svc.UserService.GetBatchUserDetails:input_type -> auth_svc.GetBatchUserDetailsReq
	3,  // 39: auth_svc.UserService.GetUserActivities:output_type -> auth_svc.UserActivityResp
	1,  // 40: auth_svc.UserService.GetUserProfile:output_type -> auth_svc.UserProfileRes
	6,  // 41: auth_svc.UserService.UpdateUserProfile:output_type -> auth_svc.UpdateUserProfileRes
	8,  // 42: auth_svc.UserService.DeleteUserAccount:output_type -> auth_svc.DeleteUserProfileRes
	11, // 43: auth_svc.UserService.GetAllTopics:output_type -> auth_svc.GetTopicsResponse
	14, // 44: auth_svc.UserService.GetAllCategories:output_type -> auth_svc.GetAllCategoriesRes
	16, // 45: auth_svc.UserService.GetUserDetails:output_type -> auth_svc.UserDetailsResp
	18, // 46: auth_svc.UserService.FollowTopics:output_type -> auth_svc.TopicActionRes
	18, // 47: auth_svc.UserService.UnFollowTopics:output_type -> auth_svc.TopicActionRes
	29, // 48: auth_svc.UserService.FollowUser:output_type -> auth_svc.UserFollowRes
	29, // 49: auth_svc.UserService.UnFollowUser:output_type -> auth_svc.UserFollowRes
	31, // 50: auth_svc.UserService.GetFollowers:output_type -> auth_svc.FollowerFollowingResp
	31, // 51: auth_svc.UserService.GetFollowing:output_type -> auth_svc.FollowerFollowingResp
	29, // 52: auth_svc.UserService.GetIfIFollowedUser:output_type -> auth_svc.UserFollowRes
	33, // 53: auth_svc.UserService.GetFollowersFollowingCounts:output_type -> auth_svc.FollowerFollowingCountsResp
	31, // 54: auth_svc.UserService.SearchUser:output_type -> auth_svc.FollowerFollowingResp
	27, // 55: auth_svc.UserService.BookMarkBlog:output_type -> auth_svc.BookMarkRes
	27, // 56: auth_svc.UserService.GetBookMarks:output_type -> auth_svc.BookMarkRes
	27, // 57: auth_svc.UserService.RemoveBookMark:output_type -> auth_svc.BookMarkRes
	27, // 58: auth_svc.UserService.LikeBlog:output_type -> auth_svc.BookMarkRes
	27, // 59: auth_svc.UserService.UnlikeBlog:output_type -> auth_svc.BookMarkRes
	27, // 60: auth_svc.UserService.GetIfBlogLiked:output_type -> auth_svc.BookMarkRes
	27, // 61: auth_svc.UserService.GetIfBlogBookMarked:output_type -> auth_svc.BookMarkRes
	32, // 62: auth_svc.UserService.GetBookMarkCounts:output_type -> auth_svc.CountResp
	32, // 63: auth_svc.UserService.GetLikeCounts:output_type -> auth_svc.CountResp
	20, // 64: auth_svc.UserService.InviteCoAuthor:output_type -> auth_svc.CoAuthorAccessRes
	20, // 65: auth_svc.UserService.RevokeCoAuthorAccess:output_type -> auth_svc.CoAuthorAccessRes
	23, // 66: auth_svc.UserService.GetBlogsByUserIds:output_type -> auth_svc.BlogsByUserNameRes
	25, // 67: auth_svc.UserService.CreateNewTopics:output_type -> auth_svc.CreateTopicsRes
	35, // 68: auth_svc.UserService.GetBatchUserDetails:output_type -> auth_svc.GetBatchUserDetailsRes
	39, // [39:69] is the sub-list for method output_type
	9,  // [9:39] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_user_pb_gw_user_proto_init() }
func file_apis_serviceconn_gateway_user_pb_gw_user_proto_init() {
	if File_apis_serviceconn_gateway_user_pb_gw_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc), len(file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_user_pb_gw_user_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_user_pb_gw_user_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_user_pb_gw_user_proto = out.File
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_goTypes = nil
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_depIdxs = nil
}
