// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: apis/serviceconn/gateway_reports/pb/gw_report.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportsService_CreateReport_FullMethodName = "/reports_svc.ReportsService/CreateReport"
)

// ReportsServiceClient is the client API for ReportsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportsServiceClient interface {
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error)
}

type reportsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportsServiceClient(cc grpc.ClientConnInterface) ReportsServiceClient {
	return &reportsServiceClient{cc}
}

func (c *reportsServiceClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReportResponse)
	err := c.cc.Invoke(ctx, ReportsService_CreateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportsServiceServer is the server API for ReportsService service.
// All implementations must embed UnimplementedReportsServiceServer
// for forward compatibility.
type ReportsServiceServer interface {
	CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error)
	mustEmbedUnimplementedReportsServiceServer()
}

// UnimplementedReportsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportsServiceServer struct{}

func (UnimplementedReportsServiceServer) CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedReportsServiceServer) mustEmbedUnimplementedReportsServiceServer() {}
func (UnimplementedReportsServiceServer) testEmbeddedByValue()                        {}

// UnsafeReportsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportsServiceServer will
// result in compilation errors.
type UnsafeReportsServiceServer interface {
	mustEmbedUnimplementedReportsServiceServer()
}

func RegisterReportsServiceServer(s grpc.ServiceRegistrar, srv ReportsServiceServer) {
	// If the following call pancis, it indicates UnimplementedReportsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportsService_ServiceDesc, srv)
}

func _ReportsService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportsService_CreateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportsService_ServiceDesc is the grpc.ServiceDesc for ReportsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reports_svc.ReportsService",
	HandlerType: (*ReportsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReport",
			Handler:    _ReportsService_CreateReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/serviceconn/gateway_reports/pb/gw_report.proto",
}
