the_monkeys_gateway:
  HTTPS: 0.0.0.0:8080
  HTTP: 0.0.0.0:8081
microservices:
  the_monkeys_authz: the_monkeys_authz:50051 # To run on the local replace with 0.0.0.0:50051
  the_monkeys_blog: the_monkeys_blog:50052   # To run on the local replace with 0.0.0.0:50052
  the_monkeys_user: the_monkeys_user:50053   # To run on the local replace with 0.0.0.0:50053
  the_monkeys_storage: the_monkeys_storage:50054    # To run on the local replace with 0.0.0.0:50054
  the_monkeys_notification: the_monkeys_notification:50055   # To run on the local replace with
postgresql:
  primary_db:
    db_username: root
    db_password: Secret
    # localhost for connecting to the local postgres server
    # the_monkeys_db for connecting to the container postgres server
    db_host: the_monkeys_db
    db_port: 5432
    db_name: the_monkeys_user_dev
  replica_1:
    db_username: root
    db_password: Secret
    db_host: 0.0.0.0
    db_port: 5432
    db_name: the_monkeys_user_dev
jwt:
  secret_key: Secret
opensearch:
  address: http://localhost:9200
  os_host: http://elasticsearch-node1:9200
  os_username: admin
  os_password: "a!Too5hortPassword@1"
email:
  smtp_address: ""
  smtp_mail: ""
  smtp_password: ""
  smtp_host: ""

authentication:
  # provide the domain name or UI: https://themonkeys.live
  email_verification_addr: http://127.0.0.1:8081

google_oauth2:
  redirect_url: "<domain>/auth/google/callback" # exmaple: https://themonkeys.live/auth/google/callback
  client_id: "<client_id>" # example: 1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
  client_secret: "<client_secret>" # example: abcdefghijklmnopqrstuvwxyz
  scope:
    - "<scope 1>" # example: https://www.googleapis.com/auth/userinfo.email
    - "<scope 2>" # example: https://www.googleapis.com/auth/userinfo.profile
  endpoint: ""  # example: google.Endpoint

rabbitMQ:
  protocol: "amqp"
  host: "rabbitmq"
  port: "5672"
  username: "myuser"
  password: "mypassword"
  virtualHost: ""
  exchange: smart_monkey
  queues:
    - "queue1"
    - "queue2"
    - "blog_svc_file_svc_queue"
    - "to_blog_svc_queue"
    - "to_notification_svc_queue"
  routingKeys:
    - "key1"
    - "key2"
    - "blog_svc_file_svc_key"
    - "to_blog_svc_key"
    - "to_notification_svc_key"

keys:
  mediastack: token
  newsapi: "token"
  hindustantimes: token

allowed_cors:
  allowed_origins:
    - "https://deploy-preview-242--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-244--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-245--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-246--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-247--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-248--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-249--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-250--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-251--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-252--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-253--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-254--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-255--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-256--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-257--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-258--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-259--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-260--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-261--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-262--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-263--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-264--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-265--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-266--incredible-eclair-ada155.netlify.app" 
    - "https://deploy-preview-267--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-268--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-269--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-270--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-271--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-272--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-273--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-274--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-275--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-276--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-277--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-278--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-279--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-280--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-281--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-282--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-283--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-284--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-285--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-286--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-287--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-288--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-289--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-290--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-291--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-292--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-293--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-294--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-295--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-296--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-297--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-298--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-299--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-300--incredible-eclair-ada155.netlify.app"
    - "https://deploy-preview-301--incredible-eclair-ada155.netlify.app" 

  allowed_ips:
    - "<ip1>"
 