the_monkeys_gateway:
  HTTPS: 0.0.0.0:8080
  HTTP: 0.0.0.0:8081
microservices:
  the_monkeys_authz: the_monkeys_authz:50051 # To run on the local replace with 0.0.0.0:50051
  the_monkeys_blog: the_monkeys_blog:50052   # To run on the local replace with 0.0.0.0:50052
  the_monkeys_user: the_monkeys_user:50053   # To run on the local replace with 0.0.0.0:50053
  the_monkeys_storage: the_monkeys_storage:50054    # To run on the local replace with 0.0.0.0:50054
  the_monkeys_notification: the_monkeys_notification:50055   # To run on the local replace with
  the_monkeys_cache: the_monkeys_cache_svc:50056   # To run on the local replace with 0.0.0.0:50056
  the_monkeys_recomm_engine: the_monkeys_recomm_engine:50057 
postgresql:
  primary_db:
    db_username: root
    db_password: Secret
    # localhost for connecting to the local postgres server
    # the_monkeys_db for connecting to the container postgres server
    db_host: the_monkeys_db
    db_port: 5432
    db_name: the_monkeys_user_dev
  replica_1:
    db_username: root
    db_password: Secret
    db_host: 0.0.0.0
    db_port: 5432
    db_name: the_monkeys_user_dev
jwt:
  secret_key: Secret
opensearch:
  address: http://localhost:9200
  os_host: http://elasticsearch-node1:9200
  os_username: admin
  os_password: "a!Too5hortPassword@1"
email:
  smtp_address: ""
  smtp_mail: ""
  smtp_password: ""
  smtp_host: ""

authentication:
  # provide the domain name or UI: https://themonkeys.live
  email_verification_addr: http://127.0.0.1:8081

google_oauth2:
  redirect_url: "<domain>/auth/google/callback" # exmaple: https://themonkeys.live/auth/google/callback
  client_id: "<client_id>" # example: 1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
  client_secret: "<client_secret>" # example: abcdefghijklmnopqrstuvwxyz
  scope:
    - "<scope 1>" # example: https://www.googleapis.com/auth/userinfo.email
    - "<scope 2>" # example: https://www.googleapis.com/auth/userinfo.profile
  endpoint: ""  # example: google.Endpoint

rabbitMQ:
  protocol: "amqp"
  host: "rabbitmq"
  port: "5672"
  username: "myuser"
  password: "mypassword"
  virtualHost: ""
  exchange: smart_monkey
  queues:
    - "queue1"
    - "queue2"
    - "blog_svc_file_svc_queue"
    - "to_blog_svc_queue"
    - "to_notification_svc_queue"
    - "to_cache_svc_queue"
  routingKeys:
    - "key1"
    - "key2"
    - "blog_svc_file_svc_key"
    - "to_blog_svc_key"
    - "to_notification_svc_key"
    - "to_cache_svc_key"
    
keys:
  mediastack: token
  newsapi: "token"
  hindustantimes: token

cors: 
  allowed_origin_regexp: '^https?://((local\\.)?monkeys.com.co|deploy-preview-\d+.*.netlify.app)(:\d+)?$'

redis:
  host: "the_monkeys_cache:6379"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  max_idle: 5
