// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/serviceconn/gateway_notification/pb/gw_notification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Seen          bool                   `protobuf:"varint,5,opt,name=seen,proto3" json:"seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetSeen() bool {
	if x != nil {
		return x.Seen
	}
	return false
}

type SendNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationReq) Reset() {
	*x = SendNotificationReq{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationReq) ProtoMessage() {}

func (x *SendNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationReq.ProtoReflect.Descriptor instead.
func (*SendNotificationReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendNotificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRes) Reset() {
	*x = SendNotificationRes{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRes) ProtoMessage() {}

func (x *SendNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRes.ProtoReflect.Descriptor instead.
func (*SendNotificationRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendNotificationRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationReq) Reset() {
	*x = GetNotificationReq{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationReq) ProtoMessage() {}

func (x *GetNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationReq.ProtoReflect.Descriptor instead.
func (*GetNotificationReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetNotificationReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetNotificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  []*Notification        `protobuf:"bytes,1,rep,name=notification,proto3" json:"notification,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRes) Reset() {
	*x = GetNotificationRes{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRes) ProtoMessage() {}

func (x *GetNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRes.ProtoReflect.Descriptor instead.
func (*GetNotificationRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationRes) GetNotification() []*Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *GetNotificationRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationReq) Reset() {
	*x = DeleteNotificationReq{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationReq) ProtoMessage() {}

func (x *DeleteNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationReq.ProtoReflect.Descriptor instead.
func (*DeleteNotificationReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNotificationReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteNotificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRes) Reset() {
	*x = DeleteNotificationRes{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRes) ProtoMessage() {}

func (x *DeleteNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRes.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotificationRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteNotificationRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Notification  []*Notification        `protobuf:"bytes,2,rep,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchNotificationReq) Reset() {
	*x = WatchNotificationReq{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchNotificationReq) ProtoMessage() {}

func (x *WatchNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchNotificationReq.ProtoReflect.Descriptor instead.
func (*WatchNotificationReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{7}
}

func (x *WatchNotificationReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WatchNotificationReq) GetNotification() []*Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apis_serviceconn_gateway_notification_pb_gw_notification_proto protoreflect.FileDescriptor

const file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDesc = "" +
	"\n" +
	">apis/serviceconn/gateway_notification/pb/gw_notification.proto\x12\x10notification_svc\"}\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04seen\x18\x05 \x01(\bR\x04seen\"H\n" +
	"\x13SendNotificationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x13SendNotificationRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"^\n" +
	"\x12GetNotificationReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"n\n" +
	"\x12GetNotificationRes\x12B\n" +
	"\fnotification\x18\x01 \x03(\v2\x1e.notification_svc.NotificationR\fnotification\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"0\n" +
	"\x15DeleteNotificationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"E\n" +
	"\x15DeleteNotificationRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"s\n" +
	"\x14WatchNotificationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12B\n" +
	"\fnotification\x18\x02 \x03(\v2\x1e.notification_svc.NotificationR\fnotification\"^\n" +
	"\x14NotificationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x93\x04\n" +
	"\x13NotificationService\x12b\n" +
	"\x10SendNotification\x12%.notification_svc.SendNotificationReq\x1a%.notification_svc.SendNotificationRes\"\x00\x12_\n" +
	"\x0fGetNotification\x12$.notification_svc.GetNotificationReq\x1a$.notification_svc.GetNotificationRes\"\x00\x12h\n" +
	"\x12DeleteNotification\x12'.notification_svc.DeleteNotificationReq\x1a'.notification_svc.DeleteNotificationRes\"\x00\x12d\n" +
	"\x10NotificationSeen\x12&.notification_svc.WatchNotificationReq\x1a&.notification_svc.NotificationResponse\"\x00\x12g\n" +
	"\x15GetNotificationStream\x12$.notification_svc.GetNotificationReq\x1a$.notification_svc.GetNotificationRes\"\x000\x01B,Z*./apis/serviceconn/gateway_notification/pbb\x06proto3"

var (
	file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescData []byte
)

func file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDesc), len(file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDesc)))
	})
	return file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDescData
}

var file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_goTypes = []any{
	(*Notification)(nil),          // 0: notification_svc.Notification
	(*SendNotificationReq)(nil),   // 1: notification_svc.SendNotificationReq
	(*SendNotificationRes)(nil),   // 2: notification_svc.SendNotificationRes
	(*GetNotificationReq)(nil),    // 3: notification_svc.GetNotificationReq
	(*GetNotificationRes)(nil),    // 4: notification_svc.GetNotificationRes
	(*DeleteNotificationReq)(nil), // 5: notification_svc.DeleteNotificationReq
	(*DeleteNotificationRes)(nil), // 6: notification_svc.DeleteNotificationRes
	(*WatchNotificationReq)(nil),  // 7: notification_svc.WatchNotificationReq
	(*NotificationResponse)(nil),  // 8: notification_svc.NotificationResponse
}
var file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_depIdxs = []int32{
	0, // 0: notification_svc.GetNotificationRes.notification:type_name -> notification_svc.Notification
	0, // 1: notification_svc.WatchNotificationReq.notification:type_name -> notification_svc.Notification
	1, // 2: notification_svc.NotificationService.SendNotification:input_type -> notification_svc.SendNotificationReq
	3, // 3: notification_svc.NotificationService.GetNotification:input_type -> notification_svc.GetNotificationReq
	5, // 4: notification_svc.NotificationService.DeleteNotification:input_type -> notification_svc.DeleteNotificationReq
	7, // 5: notification_svc.NotificationService.NotificationSeen:input_type -> notification_svc.WatchNotificationReq
	3, // 6: notification_svc.NotificationService.GetNotificationStream:input_type -> notification_svc.GetNotificationReq
	2, // 7: notification_svc.NotificationService.SendNotification:output_type -> notification_svc.SendNotificationRes
	4, // 8: notification_svc.NotificationService.GetNotification:output_type -> notification_svc.GetNotificationRes
	6, // 9: notification_svc.NotificationService.DeleteNotification:output_type -> notification_svc.DeleteNotificationRes
	8, // 10: notification_svc.NotificationService.NotificationSeen:output_type -> notification_svc.NotificationResponse
	4, // 11: notification_svc.NotificationService.GetNotificationStream:output_type -> notification_svc.GetNotificationRes
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_init() }
func file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_init() {
	if File_apis_serviceconn_gateway_notification_pb_gw_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDesc), len(file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_notification_pb_gw_notification_proto = out.File
	file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_goTypes = nil
	file_apis_serviceconn_gateway_notification_pb_gw_notification_proto_depIdxs = nil
}
