// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/serviceconn/gateway_recom/pb/gw_recom.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Client        string                 `protobuf:"bytes,6,opt,name=client,proto3" json:"client,omitempty"`
	Location      *Location              `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileReq) Reset() {
	*x = UserProfileReq{}
	mi := &file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileReq) ProtoMessage() {}

func (x *UserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileReq.ProtoReflect.Descriptor instead.
func (*UserProfileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserProfileReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfileReq) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *UserProfileReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UserProfileReq) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *UserProfileReq) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Lat           string                 `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           string                 `protobuf:"bytes,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Street        string                 `protobuf:"bytes,8,opt,name=street,proto3" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Location) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *Location) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Location) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Location) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Location) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

type RecommendationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	UsersToFollow []string               `protobuf:"bytes,2,rep,name=users_to_follow,json=usersToFollow,proto3" json:"users_to_follow,omitempty"`
	PostsToRead   []*anypb.Any           `protobuf:"bytes,3,rep,name=posts_to_read,json=postsToRead,proto3" json:"posts_to_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationRes) Reset() {
	*x = RecommendationRes{}
	mi := &file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRes) ProtoMessage() {}

func (x *RecommendationRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRes.ProtoReflect.Descriptor instead.
func (*RecommendationRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationRes) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *RecommendationRes) GetUsersToFollow() []string {
	if x != nil {
		return x.UsersToFollow
	}
	return nil
}

func (x *RecommendationRes) GetPostsToRead() []*anypb.Any {
	if x != nil {
		return x.PostsToRead
	}
	return nil
}

var File_apis_serviceconn_gateway_recom_pb_gw_recom_proto protoreflect.FileDescriptor

const file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDesc = "" +
	"\n" +
	"0apis/serviceconn/gateway_recom/pb/gw_recom.proto\x12\rgateway_recom\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\"\xdd\x01\n" +
	"\x0eUserProfileReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x16\n" +
	"\x06client\x18\x06 \x01(\tR\x06client\x123\n" +
	"\blocation\x18\a \x01(\v2\x17.gateway_recom.LocationR\blocation\"\xc9\x01\n" +
	"\bLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\tR\x03lon\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\x12\x16\n" +
	"\x06street\x18\b \x01(\tR\x06street\"\x8d\x01\n" +
	"\x11RecommendationRes\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12&\n" +
	"\x0fusers_to_follow\x18\x02 \x03(\tR\rusersToFollow\x128\n" +
	"\rposts_to_read\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\vpostsToRead2p\n" +
	"\x15RecommendationService\x12W\n" +
	"\x12GetRecommendations\x12\x1d.gateway_recom.UserProfileReq\x1a .gateway_recom.RecommendationRes\"\x00B#Z!apis/serviceconn/gateway_recom/pbb\x06proto3"

var (
	file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescData []byte
)

func file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDesc), len(file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDesc)))
	})
	return file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDescData
}

var file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_goTypes = []any{
	(*UserProfileReq)(nil),    // 0: gateway_recom.UserProfileReq
	(*Location)(nil),          // 1: gateway_recom.Location
	(*RecommendationRes)(nil), // 2: gateway_recom.RecommendationRes
	(*anypb.Any)(nil),         // 3: google.protobuf.Any
}
var file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_depIdxs = []int32{
	1, // 0: gateway_recom.UserProfileReq.location:type_name -> gateway_recom.Location
	3, // 1: gateway_recom.RecommendationRes.posts_to_read:type_name -> google.protobuf.Any
	0, // 2: gateway_recom.RecommendationService.GetRecommendations:input_type -> gateway_recom.UserProfileReq
	2, // 3: gateway_recom.RecommendationService.GetRecommendations:output_type -> gateway_recom.RecommendationRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_init() }
func file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_init() {
	if File_apis_serviceconn_gateway_recom_pb_gw_recom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDesc), len(file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_recom_pb_gw_recom_proto = out.File
	file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_goTypes = nil
	file_apis_serviceconn_gateway_recom_pb_gw_recom_proto_depIdxs = nil
}
