# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gw_recom.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gw_recom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egw_recom.proto\x12\rgateway_recom\x1a\x19google/protobuf/any.proto\"\xa0\x01\n\x0eUserProfileReq\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\n\n\x02ip\x18\x05 \x01(\t\x12\x0e\n\x06\x63lient\x18\x06 \x01(\t\x12)\n\x08location\x18\x07 \x01(\x0b\x32\x17.gateway_recom.Location\"\x8a\x01\n\x08Location\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\t\x12\x0b\n\x03lon\x18\x04 \x01(\t\x12\x10\n\x08timezone\x18\x05 \x01(\t\x12\x0e\n\x06region\x18\x06 \x01(\t\x12\x13\n\x0bpostal_code\x18\x07 \x01(\t\x12\x0e\n\x06street\x18\x08 \x01(\t\"i\n\x11RecommendationRes\x12\x0e\n\x06topics\x18\x01 \x03(\t\x12\x17\n\x0fusers_to_follow\x18\x02 \x03(\t\x12+\n\rposts_to_read\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any2p\n\x15RecommendationService\x12W\n\x12GetRecommendations\x12\x1d.gateway_recom.UserProfileReq\x1a .gateway_recom.RecommendationRes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gw_recom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPROFILEREQ']._serialized_start=61
  _globals['_USERPROFILEREQ']._serialized_end=221
  _globals['_LOCATION']._serialized_start=224
  _globals['_LOCATION']._serialized_end=362
  _globals['_RECOMMENDATIONRES']._serialized_start=364
  _globals['_RECOMMENDATIONRES']._serialized_end=469
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=471
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
